{
  "hash": "8921aa5e74bceae85c8b16b6ff4c6787",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"2: Hot Spot & Cold Spot Analysis of Bus Ridership\"\nauthor: \"Emma Chew En Chin\"\ndate: \"Oct 14, 2025\"\ndate-modified: \"last-modified\"\nformat: html\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n## 1 Overview\n\nIn this study, we utilise the following methods of **Local Measures of Spatial Autocorrelation (LMSA)** and **Emerging Hot Spot Analysis (EHSA)**, which are geospatial methodologies to analyse spatio-temporal patterns of bus ridership in Singapore.\n\nWe aim to move beyond basic mapping to identify **hotspots** (areas of high ridership concentration) and **coldspots** (areas of low ridership) . Understanding these localised patterns will provide more insight into human mobility, and infrastructure improvements for public transport planning in Singapore.\n\n**Local Measures of Spatial Autocorrelation (LMSA)** is used to identify specific locations where values are significantly grouped. Instead of providing a single summary for the entire study area, methods such as **Local Moran's I**, **Local Geary’s C**, and **Getis-Ord Gi\\***, calculate a distinct statistic for every point. From this, the local neighbourhood around the point can be tested to see if similar (or dissimiliar) values are clustered together more than random chance. The goal is to precisely map concentrated high values (hotspots) and concentrated low values (coldspots), and unusual deviations or outliers.\n\n**Emerging Hot Spot Analysis (EHSA)** is used to identify spatio-temporal changes in spatial clustering. It takes static data and converts it into a dynamic **space-time cube** to reveal how patterns are shifting. EHSA first utilizes the local Gi∗ statistic to find where the clusters (hot and cold spots) exist, then integrates the **Mann-Kendall trend test** to determine their developmental path. This combination allows for a categorisation of trends, identifying clusters that are, for example, becoming \"new,\" \"intensifying,\" or \"diminishing.\" Ultimately, EHSA provides a temporal narrative, moving beyond static analysis to explain the **dynamics and persistence** of high and low value concentrations.\n\n### 1.1 Datasets\n\n**Aspatial Data**\n\n-   *Passenger Volume by Origin Destination Bus Stops* from [LTA DataMall](https://datamall.lta.gov.sg/content/datamall/en.html)\n\n**Geospatial Data**\n\n-   *Bus Stop Location* from LTA DataMall. It provides information about all the bus stops currently being serviced by buses, including the bus stop code (identifier) and location coordinates.\n\n-   *Master Plan 2019 Subzone Boundary (No Sea)* from [Singapore’s open data portal](https://data.gov.sg/).\n\n### 1.2 Methodology\n\n**Step 1: Data Aggregation and Spatial Encoding**\nFirst, the raw bus ridership data (collected via smart cards and GPS) will be preprocessed and aggregated into a suitable spatial framework. This involves calculating the total number of passenger trips by origin and destination for defined time intervals (e.g., morning and evening peak hours, off-peak) and aggregating these counts to a defined spatial unit.\n\n**Step 2: Local Measures of Spatial Autocorrelation (LMSA)**\n\nNext, Local Measures of Spatial Autocorrelation (LMSA), specifically the Local Moran’s I, Local Geary’s C, and the Getis-Ord Gi* statistics, will be used to identify statistically significant static hotspots (high-ridership clusters) and coldspots (low-ridership clusters). \n\n**Step 3: Spatio-Temporal Analysis (EHSA)**\n\nEmerging Hot Spot Analysis (EHSA) will be conducted by organising the static Gi∗ results from all time intervals into a space-time cube. The output will classify areas into categories such as \"new,\" \"intensifying,\" \"diminishing,\" or \"sporadic\" hot and cold spots, providing dynamic insights into how bus ridership patterns are changing over time.\n\n## 2 Data Preparation\n\n### 2.1 Loading the R packages\n\nThe following R packages are used:\n\n-   `spdep`: compute spatial weights and global and local spatial autocorrelation statistics\n-   `Kendall`: conduct non-parametric trend tests and detects temporal trends in spatial patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, sf, spdep, sfdep, tmap, knitr, httr, rvest, plotly, Kendall)\n```\n:::\n\n\n### 2.2 Importing Data\n\n#### 2.2.1 Bus Stop Location\n\nAs Bus Stop location data has crs = 9001, we standardise it into crs = 3414.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBusStop = st_read(dsn = \"data/LTADataMall/\",\n                  layer = \"BusStop\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BusStop' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex2\\data\\LTADataMall' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5172 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48285.52 ymax: 52983.82\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n#### 2.2.2 Master Plan 2019 Subzone\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_sf <- st_read(\"data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaKML.kml\") %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>% st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `URA_MP19_SUBZONE_NO_SEA_PL' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex2\\data\\geospatial\\MasterPlan2019SubzoneBoundaryNoSeaKML.kml' \n  using driver `KML'\nSimple feature collection with 332 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_kml_field <- function(html_text, field_name) {\n  if (is.na(html_text) || html_text == \"\") return(NA_character_)\n  \n  page <- read_html(html_text)\n  rows <- page %>% html_elements(\"tr\")\n  \n  value <- rows %>%\n    keep(~ html_text2(html_element(.x, \"th\")) == field_name) %>%\n    html_element(\"td\") %>%\n    html_text2()\n  \n  if (length(value) == 0) NA_character_ else value\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_sf <- mpsz_sf %>%\n  mutate(\n    REGION_N = map_chr(Description, extract_kml_field, \"REGION_N\"),\n    PLN_AREA_N = map_chr(Description, extract_kml_field, \"PLN_AREA_N\"),\n    SUBZONE_N = map_chr(Description, extract_kml_field, \"SUBZONE_N\"),\n    SUBZONE_C = map_chr(Description, extract_kml_field, \"SUBZONE_C\")\n  ) %>%\n  select(-Name, -Description) %>%\n  relocate(geometry, .after = last_col())\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_cl <- mpsz_sf %>%\n  filter(SUBZONE_N != \"SOUTHERN GROUP\",\n         PLN_AREA_N != \"WESTERN ISLANDS\", \n         PLN_AREA_N != \"NORTH-EASTERN ISLANDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mpsz_cl, \n          \"data/rds/mpsz_cl.rds\")\n```\n:::\n\n\n#### 2.2.3  O-D Bus Trips\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodbus <- read_csv(\"data/LTADataMall/origin_destination_bus_202508.csv\")\n```\n:::\n\n\n##### 2.2.3.1 Visualise the Bus Stops\n\nWe see some bus stops outside the polygons. (Due to the JB border)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_cl) + \n  tm_polygons() + \n  tm_shape(BusStop) + \n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n##### 2.2.3.2 Extract Bus Stops within Singapore\n\nWe do not use left join as we only want to get bus stops within mpsz.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBusStop_in_SG <- st_join(\n  BusStop, mpsz_cl,\n  join = st_within,\n  left = FALSE)\n```\n:::\n\n\nPlot the bus stop data again to check that the bus stops have been removed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_cl) + \n  tm_polygons() + \n  tm_shape(BusStop_in_SG) + \n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n##### 2.2.3.3 Deriving Analytical Hexagon\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon <- st_make_grid(mpsz_cl,\n                        cellsize = 750,\n                        what = \"polygon\",\n                        square = FALSE) %>%\n  st_sf()\n```\n:::\n\n\n##### 2.2.3.4 Filtering hexagons with bus stops\n\n`n_collisions` counts the number of bus stops in each hexagon.\nOnly retain hexagons with bus stops.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon$n_collisions =\n  lengths(st_intersects(\n    hexagon, BusStop_in_SG))\n\nhexagon <- filter(hexagon, n_collisions > 0)\n```\n:::\n\n\n##### 2.2.3.5 Assigning ids to each hexagon\n\nCreate id for each hexagon as previous hexagon table has no id.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon <- hexagon %>%\n  select(,-n_collisions)\n\nhexagon$HEX_ID <- sprintf(\n  \"H%04d\", seq_len(nrow(hexagon))) %>%\n  as.factor()\n\nkable(head(hexagon))\n```\n\n::: {.cell-output-display}\n\n\n|geometry                       |HEX_ID |\n|:------------------------------|:------|\n|POLYGON ((4167.538 27510.65... |H0001  |\n|POLYGON ((4167.538 30108.73... |H0002  |\n|POLYGON ((4542.538 28160.17... |H0003  |\n|POLYGON ((4542.538 29459.21... |H0004  |\n|POLYGON ((4542.538 30758.25... |H0005  |\n|POLYGON ((4917.538 28809.69... |H0006  |\n\n\n:::\n:::\n\n\n#### 2.2.4 Preparing Trip Generation Data\n\nWe are only interested in ORIGIN_PT_CODE (trip origin).\n\n##### 2.2.4.1 Cleaning the data\n\nUnnecessary columns are removed\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips <- odbus %>%\n  select(c(ORIGIN_PT_CODE, DAY_TYPE, TIME_PER_HOUR, TOTAL_TRIPS)) %>%\n  rename(BUS_STOP_N = ORIGIN_PT_CODE) %>%\n  rename(HOUR_OF_DAY = TIME_PER_HOUR) %>%\n  rename(TRIPS = TOTAL_TRIPS)\ntrips$BUS_STOP_N <- as.factor(trips$BUS_STOP_N)\nkable(head(trips))\n```\n\n::: {.cell-output-display}\n\n\n|BUS_STOP_N |DAY_TYPE         | HOUR_OF_DAY| TRIPS|\n|:----------|:----------------|-----------:|-----:|\n|84671      |WEEKENDS/HOLIDAY |           9|     3|\n|10099      |WEEKENDS/HOLIDAY |          13|    31|\n|64601      |WEEKENDS/HOLIDAY |          21|     3|\n|53009      |WEEKENDS/HOLIDAY |          16|    10|\n|80051      |WEEKENDS/HOLIDAY |          18|     4|\n|70031      |WEEKDAY          |          14|     1|\n\n\n:::\n:::\n\n\n##### 2.2.4.2 Combining bus stop and hexagon layers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbs_hex <-st_intersection(\n  BusStop, hexagon) %>%\n  st_drop_geometry() %>%\n  select(c(BUS_STOP_N, HEX_ID))\nkable(head(bs_hex))\n```\n\n::: {.cell-output-display}\n\n\n|     |BUS_STOP_N |HEX_ID |\n|:----|:----------|:------|\n|3092 |25059      |H0001  |\n|241  |26379      |H0002  |\n|2439 |25751      |H0003  |\n|2554 |25761      |H0003  |\n|2650 |25719      |H0004  |\n|2651 |25711      |H0004  |\n\n\n:::\n:::\n\n\n##### 2.2.4.3 Adding Hex_ID into bus trips data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips <- inner_join(trips, bs_hex)\nkable(head(trips))\n```\n\n::: {.cell-output-display}\n\n\n|BUS_STOP_N |DAY_TYPE         | HOUR_OF_DAY| TRIPS|HEX_ID |\n|:----------|:----------------|-----------:|-----:|:------|\n|84671      |WEEKENDS/HOLIDAY |           9|     3|H0751  |\n|10099      |WEEKENDS/HOLIDAY |          13|    31|H0387  |\n|64601      |WEEKENDS/HOLIDAY |          21|     3|H0617  |\n|53009      |WEEKENDS/HOLIDAY |          16|    10|H0507  |\n|80051      |WEEKENDS/HOLIDAY |          18|     4|H0583  |\n|70031      |WEEKDAY          |          14|     1|H0614  |\n\n\n:::\n:::\n\n\n#### 2.2.5 Create Total Trips per Hexagon dataset\n\nThis section prepares the data for **Local Measures of Spatial Association (LMSA)** analysis. We join the hexagon spatial data with the aggregated total trips data within each hexagon using **HEX_ID**. This dataset allows us to effectively visualise the spatial distribution of total bus ridership.\n\n##### 2.2.5.1 Aggregate Trip Data by Hexagon\n\nWithin *trips* dataset, we calculate the total TRIPS per hexagon (\"HEX_ID\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_agg <- trips %>%\n  group_by(HEX_ID) %>%\n  summarise(total_trips = sum(TRIPS, na.rm = TRUE),\n            .groups = 'drop')\n\nkable(head(trips_agg))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID | total_trips|\n|:------|-----------:|\n|H0001  |        4144|\n|H0002  |         960|\n|H0003  |        2708|\n|H0004  |        7645|\n|H0005  |        1060|\n|H0006  |         831|\n\n\n:::\n:::\n\n\n##### 2.2.5.2 Relational Join \n\nJoin *trips_agg* with *hexagon* on \"HEX_ID\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_trips <- hexagon %>%\n  inner_join(trips_agg, by = \"HEX_ID\") %>%\n  mutate(total_trips = replace_na(total_trips, 0))\n\nkable(head(hexagon_trips))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID | total_trips|geometry                       |\n|:------|-----------:|:------------------------------|\n|H0001  |        4144|POLYGON ((4167.538 27510.65... |\n|H0002  |         960|POLYGON ((4167.538 30108.73... |\n|H0003  |        2708|POLYGON ((4542.538 28160.17... |\n|H0004  |        7645|POLYGON ((4542.538 29459.21... |\n|H0005  |        1060|POLYGON ((4542.538 30758.25... |\n|H0006  |         831|POLYGON ((4917.538 28809.69... |\n\n\n:::\n:::\n\n\n##### 2.2.5.3 Removing Disjointed Subgraphs from Total Trips Data\n\nAfter creating the main analytical dataset, we identify and remove disjointed subgraphs to ensure a connected spatial network for accurate spatial autocorrelation analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create initial weights to identify connected components\nhexagon_trips_weights <- hexagon_trips %>%\n  mutate(nb = st_contiguity(geometry))\n\n# Identify connected components\ncomponents <- n.comp.nb(hexagon_trips_weights$nb)\ncomponent_sizes <- table(components$comp.id)\n\nprint(\"Connected component sizes:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Connected component sizes:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(component_sizes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4   5 \n799   7   2   2   2 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Keep only the largest connected component\nmain_component_id <- which.max(component_sizes)\nhexagon_trips <- hexagon_trips[components$comp.id == main_component_id, ]\n\ncat(\"Retained component\", main_component_id, \"with\", nrow(hexagon_trips), \"hexagons\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRetained component 1 with 799 hexagons\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Removed\", sum(component_sizes) - nrow(hexagon_trips), \"hexagons from disjoint subgraphs\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRemoved 13 hexagons from disjoint subgraphs\n```\n\n\n:::\n:::\n\n\n#### 2.2.6 Create Total Trips per Hexagon and Peak Hour Period dataset\n\nThis section prepares the data for **Emerging Hot Spot Analysis (EHSA)**. We perform a spatial join to link the `hexagon` grid geometries with the aggregated bus trips data. By preserving the `HOUR_OF_DAY` dimension and calculating the total trips in each Peak Hour Period, we successfully build the spatio-temporal dataset required for constructing the space-time cube.\n\n##### 2.2.6.1 Aggregate Trip Data by Hexagon\n\nWithin *trips* dataset, we calculate the total TRIPS per hexagon (\"HEX_ID\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_peak <- trips %>%\n  mutate(\n    # Ensure DAY_TYPE is a character/factor for matching\n    DAY_TYPE = as.character(DAY_TYPE),\n    # Ensure HOUR_OF_DAY is numeric for range checking (e.g., 6, 9, 17)\n    HOUR_OF_DAY = as.numeric(HOUR_OF_DAY)\n  ) %>%\n  \n  mutate(\n    Peak_Period = case_when(\n      # WEEKDAY Morning Peak: 6am to 9am (inclusive)\n      DAY_TYPE == \"WEEKDAY\" & HOUR_OF_DAY >= 6 & HOUR_OF_DAY <= 9 ~ \"Weekday Morning Peak\",\n      # WEEKDAY Afternoon Peak: 5pm to 8pm (inclusive)\n      DAY_TYPE == \"WEEKDAY\" & HOUR_OF_DAY >= 17 & HOUR_OF_DAY <= 20 ~ \"Weekday Afternoon Peak\",\n      # WEEKEND/HOLIDAY Peak: 11am to 8pm (inclusive)\n      (DAY_TYPE == \"WEEKENDS/HOLIDAY\" | DAY_TYPE == \"HOLIDAY\") & HOUR_OF_DAY >= 11 & HOUR_OF_DAY <= 20 ~ \"Weekend/Holiday Peak\",\n      # Everything else is Off-Peak\n      TRUE ~ \"Off-Peak\"\n    )\n  )\n\nkable(head(trips_peak))\n```\n\n::: {.cell-output-display}\n\n\n|BUS_STOP_N |DAY_TYPE         | HOUR_OF_DAY| TRIPS|HEX_ID |Peak_Period          |\n|:----------|:----------------|-----------:|-----:|:------|:--------------------|\n|84671      |WEEKENDS/HOLIDAY |           9|     3|H0751  |Off-Peak             |\n|10099      |WEEKENDS/HOLIDAY |          13|    31|H0387  |Weekend/Holiday Peak |\n|64601      |WEEKENDS/HOLIDAY |          21|     3|H0617  |Off-Peak             |\n|53009      |WEEKENDS/HOLIDAY |          16|    10|H0507  |Weekend/Holiday Peak |\n|80051      |WEEKENDS/HOLIDAY |          18|     4|H0583  |Weekend/Holiday Peak |\n|70031      |WEEKDAY          |          14|     1|H0614  |Off-Peak             |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_agg_peak <- trips_peak %>%\n  group_by(HEX_ID, Peak_Period) %>%\n  summarise(\n    total_trips = sum(TRIPS, na.rm = TRUE),\n    .groups = 'drop'\n  )\n\nkable(head(trips_agg_peak))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID |Peak_Period            | total_trips|\n|:------|:----------------------|-----------:|\n|H0001  |Off-Peak               |        1360|\n|H0001  |Weekday Afternoon Peak |        1111|\n|H0001  |Weekday Morning Peak   |         374|\n|H0001  |Weekend/Holiday Peak   |        1299|\n|H0002  |Off-Peak               |         467|\n|H0002  |Weekday Afternoon Peak |         234|\n\n\n:::\n:::\n\n\n##### 2.2.6.2 Relational Join \n\nJoin *trips_agg_peak* with *hexagon* on \"HEX_ID\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_trips_peak <- hexagon %>%\n  inner_join(trips_agg_peak, by = \"HEX_ID\") %>%\n  mutate(total_trips = replace_na(total_trips, 0))\n\nkable(head(hexagon_trips_peak))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID |Peak_Period            | total_trips|geometry                       |\n|:------|:----------------------|-----------:|:------------------------------|\n|H0001  |Off-Peak               |        1360|POLYGON ((4167.538 27510.65... |\n|H0001  |Weekday Afternoon Peak |        1111|POLYGON ((4167.538 27510.65... |\n|H0001  |Weekday Morning Peak   |         374|POLYGON ((4167.538 27510.65... |\n|H0001  |Weekend/Holiday Peak   |        1299|POLYGON ((4167.538 27510.65... |\n|H0002  |Off-Peak               |         467|POLYGON ((4167.538 30108.73... |\n|H0002  |Weekday Afternoon Peak |         234|POLYGON ((4167.538 30108.73... |\n\n\n:::\n:::\n\n\n##### 2.2.6.3 Removing Disjointed Subgraphs from Peak Hour Data\n\nWe apply the same cleaning to the peak hour dataset to maintain consistency across all analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create initial weights to identify connected components\nhexagon_trips_peak_weights <- hexagon_trips_peak %>%\n  mutate(nb = st_contiguity(geometry))\n\n# Identify connected components\ncomponents_peak <- n.comp.nb(hexagon_trips_peak_weights$nb)\ncomponent_sizes_peak <- table(components_peak$comp.id)\n\nprint(\"Connected component sizes for peak data:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Connected component sizes for peak data:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(component_sizes_peak)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4    5 \n3183   28    8    8    8 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Keep only the largest connected component\nmain_component_id_peak <- which.max(component_sizes_peak)\nhexagon_trips_peak <- hexagon_trips_peak[components_peak$comp.id == main_component_id_peak, ]\n\ncat(\"Retained component\", main_component_id_peak, \"with\", nrow(hexagon_trips_peak), \"hexagons\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRetained component 1 with 3183 hexagons\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Removed\", sum(component_sizes_peak) - nrow(hexagon_trips_peak), \"hexagons from disjoint subgraphs\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRemoved 52 hexagons from disjoint subgraphs\n```\n\n\n:::\n:::\n\n\n#### 2.2.7 Create Total Trips per Hexagon per Hour Dataset\n\nThis section prepares the data for **Emerging Hot Spot Analysis (EHSA)**. We aggregate trips by both hexagon and hour to create a spatio-temporal dataset that will form the space-time cube.\n\n##### 2.2.7.1 Aggregate Trip Data by Hexagon and Hour\n\nWithin *trips* dataset, we calculate the total TRIPS per hexagon (\"HEX_ID\") per hour (\"HOUR_OF_DAY\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_agg_hourly <- trips %>%\n  group_by(HEX_ID, HOUR_OF_DAY) %>%\n  summarise(total_trips = sum(TRIPS, na.rm = TRUE),\n            .groups = 'drop')\n\nkable(head(trips_agg_hourly))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID | HOUR_OF_DAY| total_trips|\n|:------|-----------:|-----------:|\n|H0001  |           6|         234|\n|H0001  |           7|         192|\n|H0001  |           8|         203|\n|H0001  |           9|         198|\n|H0001  |          10|         142|\n|H0001  |          11|         196|\n\n\n:::\n:::\n\n\n##### 2.2.7.2 Relational Join \n\nJoin *trips_agg_hourly* with hexagon on \"HEX_ID\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_trips_hourly <- hexagon %>%\n  inner_join(trips_agg_hourly, by = \"HEX_ID\") %>%\n  mutate(total_trips = replace_na(total_trips, 0))\n\nkable(head(hexagon_trips_hourly))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID | HOUR_OF_DAY| total_trips|geometry                       |\n|:------|-----------:|-----------:|:------------------------------|\n|H0001  |           6|         234|POLYGON ((4167.538 27510.65... |\n|H0001  |           7|         192|POLYGON ((4167.538 27510.65... |\n|H0001  |           8|         203|POLYGON ((4167.538 27510.65... |\n|H0001  |           9|         198|POLYGON ((4167.538 27510.65... |\n|H0001  |          10|         142|POLYGON ((4167.538 27510.65... |\n|H0001  |          11|         196|POLYGON ((4167.538 27510.65... |\n\n\n:::\n:::\n\n\n##### 2.2.7.3 Removing Disjointed Subgraphs from Hourly Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_trips_hourly_clean <- hexagon_trips_hourly[components$comp.id == main_component_id, ]\n\ncat(\"Original hourly dataset:\", nrow(hexagon_trips_hourly), \"hexagon-hour combinations\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOriginal hourly dataset: 16279 hexagon-hour combinations\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cleaned hourly dataset: \", nrow(hexagon_trips_hourly_clean), \"hexagon-hour combinations\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCleaned hourly dataset:  16019 hexagon-hour combinations\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Removed\", nrow(hexagon_trips_hourly) - nrow(hexagon_trips_hourly_clean), \"hexagon-hour combinations from disjoint subgraphs\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRemoved 260 hexagon-hour combinations from disjoint subgraphs\n```\n\n\n:::\n:::\n\n\n#### 2.2.8 Visualising Bus Ridership in Singapore\n\nUsing **tmap**, we can plot and visualise multiple choropleth maps using equal, quantile, kmeans, headtails classification methods.\n\n##### 2.2.8.1 Plotting Overall Bus Ridership\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmall_legend_layout <- tm_layout(\n  legend.text.size = 0.4, \n  legend.title.size = 0.6,\n  legend.position = c(\"left\", \"bottom\") \n)\n\nequal <- tm_shape(hexagon_trips) +\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"Total Bus Trips\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Equal interval classification\") +\n  small_legend_layout\n\nquantile <- tm_shape(hexagon_trips) +\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"Total Bus Trips\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Quantile interval classification\") +\n  small_legend_layout\n\nkmeans <- tm_shape(hexagon_trips) +\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(\n                style = \"kmeans\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"Total Bus Trips\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"K-means interval classification\") +\n  small_legend_layout\n\nheadtails <- tm_shape(hexagon_trips) +\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(\n                style = \"headtails\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"Total Bus Trips\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Headtails interval classification\") +\n  small_legend_layout\n\ntmap_arrange(equal, \n             quantile,\n             kmeans,\n             headtails,\n             asp=2, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nThe visualisations show that the bus ridership data is heavily skewed, with a few areas exhibiting extremely high trip counts (a 'heavy tail' distribution).\n\nAcross the four methods, **Headtails interval classification** provides the most meaningful representation, as it effectively separates the high-ridership hot spots from the majority of lower-activity areas.\n\nThe **Headtails interval classification** map pinpoints major hotspots in the North, East, Central and West.\n\n##### 2.2.8.2 Plotting Bus Ridership by Peak Period\n\nWe plot the Bus Ridership in Singapore by Peak Period using **Headtails interval classification** to cater to our skewed data distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter data for each peak period\nmorning_peak <- hexagon_trips_peak %>% \n  filter(Peak_Period == \"Weekday Morning Peak\")\n\nafternoon_peak <- hexagon_trips_peak %>% \n  filter(Peak_Period == \"Weekday Afternoon Peak\")\n\nweekend_peak <- hexagon_trips_peak %>% \n  filter(Peak_Period == \"Weekend/Holiday Peak\")\n\noff_peak <- hexagon_trips_peak %>% \n  filter(Peak_Period == \"Off-Peak\")\n\n# Create headtails maps for each period\nmorning_map <- tm_shape(morning_peak) +\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(\n                style = \"headtails\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Total Trips\")) + \n  tm_borders(col = \"grey\", alpha = 0.3) +\n  tm_title(\"Weekday Morning Peak (6-9am)\")\n\nafternoon_map <- tm_shape(afternoon_peak) +\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(\n                style = \"headtails\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Total Trips\")) + \n  tm_borders(col = \"grey\", alpha = 0.3) +\n  tm_title(\"Weekday Afternoon Peak (5-8pm)\")\n\nweekend_map <- tm_shape(weekend_peak) +\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(\n                style = \"headtails\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Total Trips\")) + \n  tm_borders(col = \"grey\", alpha = 0.3) +\n  tm_title(\"Weekend/Holiday Peak (11am-8pm)\")\n\noff_peak_map <- tm_shape(off_peak) +\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(\n                style = \"headtails\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Total Trips\")) + \n  tm_borders(col = \"grey\", alpha = 0.3) +\n  tm_title(\"Off-Peak Hours\")\n\ntmap_arrange(morning_map, afternoon_map, \n             weekend_map, off_peak_map,\n             asp = 1, \n             ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nFor the Weekday Morning and Afternoon peak periods, we see a hot spot in the West and North. Whereas in the Weekend/Holiday peak and Off-peak hours, we see additional hotspots appearing in the North, and also East. \n\n## 3 Local Measures of Spatial Autocorrelation (LMSA)\n\nIn this section, we will use **Local Measures of Spatial Autocorrelation (LMSA)**, specifically the Local Moran’s I, Local Geary’s C, and the Getis-Ord Gi* statistics, to identify statistically significant static hotspots (high-ridership clusters) and coldspots (low-ridership clusters) for each defined time interval. \n\n### 3.1 Computing Contiguity Spatial Weights\n\nFirst, we will construct spatial weights of the study area for local spatial autocorrelation statistics. The spatial weights is used to define the neighbourhood relationships between the geographical units (i.e. hexagons) in the study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- hexagon_trips %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb, style = \"W\"),\n         .before = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(wm_q$nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 799 \nNumber of nonzero links: 3874 \nPercentage nonzero weights: 0.6068286 \nAverage number of links: 4.848561 \nLink number distribution:\n\n  1   2   3   4   5   6 \n  8  32 101 143 163 352 \n8 least connected regions:\n1 306 321 378 455 650 672 750 with 1 link\n352 most connected regions:\n7 12 15 17 23 29 31 32 35 38 41 44 45 46 47 50 51 52 53 56 57 59 61 62 65 70 71 78 85 86 90 91 96 97 98 102 103 104 106 107 108 112 113 114 116 117 118 122 123 124 126 127 133 141 151 158 159 165 166 167 169 176 177 178 179 180 181 187 188 189 192 193 196 198 199 200 204 207 209 210 212 213 217 219 229 230 231 234 238 239 248 249 250 257 258 268 269 275 278 279 280 283 284 285 286 287 291 294 295 296 298 299 302 303 308 311 314 315 318 323 324 331 343 344 350 351 360 361 368 369 370 376 380 381 388 390 391 392 399 402 411 413 417 423 424 425 428 429 434 435 438 439 444 445 448 449 450 453 458 459 462 463 464 465 466 467 470 471 472 474 475 476 477 481 482 483 484 485 486 487 488 489 495 496 497 498 499 500 501 502 505 506 507 508 509 510 511 512 517 518 519 520 521 522 523 530 531 532 533 534 535 542 543 544 545 546 547 553 554 555 556 557 558 559 560 561 564 565 566 567 568 569 570 574 575 576 577 578 580 581 585 586 587 588 591 592 594 595 596 597 598 599 603 604 605 608 609 610 611 612 615 616 621 624 625 626 631 633 634 635 638 639 642 643 644 646 653 654 655 657 659 661 662 664 665 666 670 674 675 676 682 683 686 687 688 689 694 695 699 700 701 705 706 712 713 715 716 719 720 721 722 723 725 726 727 728 729 730 732 733 734 735 736 738 739 740 741 742 746 747 748 753 754 755 756 757 758 761 762 763 766 767 768 769 770 771 772 773 778 779 784 785 with 6 links\n```\n\n\n:::\n:::\n\n\nThe summary report above shows that there are 799 hexagons with an average of 4.8 neighbours per hexagon. The connectivity distribution shows 352 hexagons have the maximum of 6 neighbours, while only 8 are connected with 1 neighbour. \n\n### 3.2 Row-standardised weights matrix\n\nNext, we will assign weights to the neighbouring polygons defined by contiguity using the spatial weights matrix (**W**).\n\nIn **Row-standardised weights**, we assign an equal fraction of influence to each neighbor, so that the sum of all weights for any given hexagon equals 1 ($1/(\\text{Number of Neighbors})$).\n\nThis prevents hexagons with many neighbors from unfairly dominating the spatial autocorrelation results and is useful in our highly skewed dataset.\n\n### 3.3 Computing Local Moran's I\n\nTo identify localised spatial patterns of similarity (clustering), we compute Local Moran's I, *Ii*, the Local Indicator of Spatial Association (LISA) statistic. This is done using the *st_local_moran()* function from the **sfdep** package.This function requires the hexagon attribute data (e.g., *total_trips*) and the row-standardised spatial weights list (*Wt*).\n\nThe resulting *Ii* value measures the degree of similarity between a hexagon and its neighbors. Its interpretation is direct:\n\n-   A value of *Ii* > 0 indicates strong positive autocorrelation (High-High or Low-Low clustering/similarity).\n-   A value of *Ii* < 0 indicates strong negative autocorrelation (High-Low or Low-High dissimilarity/outliers).\n-   A value near 0 suggests no spatial autocorrelation.\n\nWe will use the associated p-values to generate a final LISA Cluster Map, which visually classifies all statistically significant hot spots, cold spots, and spatial outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- wm_q %>% \n  mutate(local_moran = local_moran(\n    total_trips, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\n\nglimpse(lisa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 799\nColumns: 17\n$ ii           <dbl> 0.4442720, 0.4500114, 0.4408824, 0.4342984, 0.4375312, 0.…\n$ eii          <dbl> -0.112351328, 0.001629808, 0.008335364, -0.030978354, -0.…\n$ var_ii       <dbl> 0.90711653, 0.13043368, 0.17700049, 0.10817105, 0.1804859…\n$ z_ii         <dbl> 0.5844264, 1.2415178, 1.0281254, 1.4146722, 1.1889484, 1.…\n$ p_ii         <dbl> 0.55893345, 0.21441453, 0.30389082, 0.15716462, 0.2344599…\n$ p_ii_sim     <dbl> 0.18, 0.04, 0.02, 0.02, 0.06, 0.02, 0.02, 0.06, 0.02, 0.0…\n$ p_folded_sim <dbl> 0.09, 0.02, 0.01, 0.01, 0.03, 0.01, 0.01, 0.03, 0.01, 0.0…\n$ skewness     <dbl> -3.9229501, -1.1854704, -2.9853972, -1.7144053, -1.871173…\n$ kurtosis     <dbl> 19.3830444, 1.0116675, 12.3602836, 3.6818658, 4.0965788, …\n$ mean         <fct> Low-Low, Low-Low, Low-Low, Low-Low, Low-Low, Low-Low, Low…\n$ median       <fct> Low-Low, Low-Low, Low-Low, Low-Low, Low-Low, Low-Low, Low…\n$ pysal        <fct> Low-Low, Low-Low, Low-Low, Low-Low, Low-Low, Low-Low, Low…\n$ nb           <nb> 3, <4, 5, 7>, <1, 6, 10>, <2, 6, 7, 11>, <2, 7, 8, 12>, <3…\n$ wt           <list> 1, <0.3333333, 0.3333333, 0.3333333>, <0.3333333, 0.3333…\n$ HEX_ID       <fct> H0001, H0002, H0003, H0004, H0005, H0006, H0007, H0008, H…\n$ total_trips  <dbl> 4144, 960, 2708, 7645, 1060, 831, 3303, 1020, 28032, 1077…\n$ geometry     <POLYGON [m]> POLYGON ((4167.538 27510.65..., POLYGON ((4167.53…\n```\n\n\n:::\n:::\n\n\n#### 3.3.1 Mapping the local Moran’s I values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"brewer.RdBu\"),\n              fill.legend = tm_legend(\n                title = \"Local Morans'I\",\n                position = tm_pos_out())) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Local Moran's I of Bus Ridership (Queen's method)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nWe can observe that the map is predominantly light-colored (light blue, white, and light orange), with the majority of hexagons falling into the -1 to 1 range.\n\nThere are some areas of spatial clustering (dark blue), which indicate High-High clusters, in the East, Central and West areas.\n\nWe also observe in the North area some negative spatial autocorrelation (dark orange) which may indicate High-Low clusters.\n\n#### 3.3.2 Mapping local Moran’s I p-values\n\nThe previous map shows that there are both positive and negative Ii values. However we can plot the p-values to understand the significance of these observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_polygons(fill = \"p_ii\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n      position = tm_pos_out())) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of Loal Moran's I of Bus Ridership (Queen's method)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nFrom the p-values in the map, we can observe that the areas with high p-value correspond to the areas of spatial clustering.\n\n#### 3.3.3 Mapping both local Moran’s I values and p-values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"brewer.RdBu\"),\n              fill.legend = tm_legend(\n                title = \"Local Moran's I\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Local Moran's I of Bus Ridership (Queen's method)\")\n\np_ii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"p_ii\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n      position = tm_pos_in(\"left\", \"bottom\")\n    )) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of Local Moran's I of Bus Ridership (Queen's method)\")\n\ntmap_arrange(ii.map, p_ii.map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n#### 3.3.4 Preparing and Visualising LISA Map\n\nLISA maps includes choropleth maps showing LISA values, Moran scatterplots which depict local spatial autocorrelation for individual locations, and hot spot analysis maps.\n\n##### 3.3.4.1 Plotting Moran scatterplot\n\nThe Moran scatterplot visualises the relationship between a variable’s values and the average values of its neighboring locations (its spatial lag) to identify spatial autocorrelation.\n\n`st_lag()` of **sfdep** package is used to calculates the spatial lag of GDPPC given a neighbor (i.e. nb) and weights list (i.e. wt).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(lag_trips = st_lag(\n    total_trips, nb, wt),\n    .before = 1) %>%\n  unnest(lag_trips)\n```\n:::\n\n\nThe Moran Scatterplot of total_trips is plotted against its spatial lag version.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = total_trips, \n           y = lag_trips)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"red\") +\n  labs(x = \"Total_Trips\",\n       y = \"Spatial Lag of Total_Trips\",\n       title = \"Moran Scatterplot\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nFrom the scatterplot, we can observe that the trend line shows a positive relationship between Total_Trips and its spatial lag version, indicating positive global spatial autocorrelation. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = total_trips, \n           y = lag_trips, \n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"black\") +\n  geom_hline(yintercept=mean(lisa$lag_trips), lty=2) + \n    geom_vline(xintercept=mean(lisa$total_trips), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\", \n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\", \n               \"High-Low\" = \"pink\")) +\n  labs(x = \"Total_Trips\",\n       y = \"Spatial Lag of Total_Trips\",\n       title = \"Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nFrom the Moran scatterplot with LISA Quadrants, we can understand that Low-Low and High-High clusters are more prevalant, and there is a high incidence of prominent outliers in the form of Low-High clusters.\n\n##### 3.3.4.2 Plotting Moran scatterplot with standardised variable\n\nscale() is used to center and scale the variable. Centering is implemented by subtracting the mean (omitting NAs), and scaling is done by dividing the (centered) variable by their standard deviations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(z_trips = scale(total_trips),\n         z_lag_trips = scale(lag_trips),\n         .before = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = z_trips, \n           y = z_lag_trips, \n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"black\") +\n  geom_hline(yintercept=mean(lisa$z_lag_trips), lty=2) + \n    geom_vline(xintercept=mean(lisa$z_trips), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\", \n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\", \n               \"High-Low\" = \"pink\")) +\n  labs(x = \"Standardised Total_Trips\",\n       y = \"Standardised Spatial Lag of Total_Trips\",\n       title = \"Standardised Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nAfter applying standardisation, the output findings remain the same.\n\n##### 3.3.4.3 Preparing LISA map classes\n\nWe will set a statistical significance level for the local Moran.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignif <- 0.05  \n```\n:::\n\n\n##### 3.3.4.4 Plotting and visualising LISA map\n\nBy default, the LISA classes are stored in *mean*, *median* and *pysal* fields of lisa sf data frame. To prepare the LISA map, we will derive a new field called LISA-cluster from either one of these three fields.\n\nA new class 'insignificant' has been added for records where p_ii \\> 0.05.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(\n    LISA_cluster = ifelse(\n      p_ii < 0.05,\n      as.character(mean), \n      \"Insignificant\"),\n    LISA_cluster = factor(\n      LISA_cluster,\n      levels = c(\"Insignificant\", \"Low-Low\", \"Low-High\", \"High-Low\", \"High-High\")\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(\n    moran_categorized = case_when(\n      p_ii > 0.05 ~ \"Not Significant\",\n      ii > 2 ~ \"Strong Positive\",\n      ii > 1 & ii <= 2 ~ \"Moderate Positive\",\n      ii > -0.5 & ii <= 1 ~ \"Weak/Random\", \n      ii > -1 & ii <= -0.5 ~ \"Moderate Negative\",\n      ii <= -1 ~ \"Strong Negative\",\n      TRUE ~ \"Not Significant\"\n    ),\n    moran_categorized = factor(\n      moran_categorized,\n      levels = c(\n        \"Strong Positive\",     \n        \"Moderate Positive\",   \n        \"Weak/Random\",         \n        \"Moderate Negative\",   \n        \"Strong Negative\",     \n        \"Not Significant\"      \n      )\n    )\n  )\n\n\nii.map <- tm_shape(lisa) +\n  tm_polygons(\n    fill = \"moran_categorized\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"Strong Positive\" = \"#b2182b\",    # Dark red\n        \"Moderate Positive\" = \"#ef8a62\",  # Medium red\n        \"Weak/Random\" = \"#fddbc7\",        # Light red/beige\n        \"Moderate Negative\" = \"#67a9cf\",  # Medium blue\n        \"Strong Negative\" = \"#2166ac\",    # Dark blue\n        \"Not Significant\" = \"grey80\"      # Grey\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"Local Moran's I\\n(p < 0.05)\",\n      position = tm_pos_in(\"left\", \"bottom\")\n    )\n  ) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Local Moran's I Values (p < 0.05)\")\n\nlisa_map <- tm_shape(lisa) + \n  tm_polygons(\n    fill = \"LISA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"blue\",        # Low-Low\n        \"lightblue\",   # Low-High\n        \"pink\",        # High-Low\n        \"red\"          # High-High\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"LISA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_borders() +\n  tm_title(\"Local Moran's I Clusters (p < 0.05)\")\n\ntmap_arrange(ii.map, lisa_map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\nFrom local Moran's I values, we can see strong positive autocorrelation in the West, Northeast and East.\n\nWe can observe many statistically significant high-high clusters across the map appearing distinctly in the East/Northeast, Central, and isolated pockets in the West.\n\n### 3.4 Computing Local Geary's C\n\nTo assess the presence of localised spatial patterns of dissimilarity, we compute Local Geary's C, *Ci*, using the `st_local_geary()` function from the **sfdep** package.\n\nThe resulting *Ci* value provides a measure of dissimilarity between a hexagon and its neighbors. Its interpretation is inverse to Local Moran's I:\n\n-   A value of *Ci* close to 0 indicates strong positive autocorrelation (High-High or Low-Low clustering/similarity).\n-   A value of *Ci* close to 2 indicates strong negative autocorrelation (High-Low or Low-High dissimilarity/outliers).\n-   A value near 1 suggests no spatial autocorrelation.\n\n#### 3.4.1 Creating Local Geary's C statistics\n\nFirst, we apply log transformation to *total_trips* as it is right skewed. \n\nA right-skewed distribution will affect Geary's C calculation, as very high values will dominate, affecting the squared difference calculation, and local clustering of moderate values may not be detected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the transformed data if it doesn't exist\nif (!exists(\"wm_q_transformed\")) {\n  wm_q_transformed <- wm_q %>%\n    mutate(log_trips = log(total_trips + 1))\n}\n\n# Use only wm_q and wm_q_transformed for the comparison\ncombined_data <- bind_rows(\n  wm_q %>% \n    select(HEX_ID, total_trips, geometry) %>%\n    mutate(type = \"Original\", value = total_trips),\n  wm_q_transformed %>% \n    select(HEX_ID, total_trips, log_trips, geometry) %>%\n    mutate(type = \"Log-Transformed\", value = log_trips)\n)\n\nggplot(combined_data, aes(x = value)) +\n  geom_histogram(bins = 30) +\n  facet_wrap(~type, scales = \"free\") +\n  labs(title = \"Distribution Comparison of Total_Trips\", x = \"Value\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlocal_geary_results <- wm_q_transformed %>%\n  mutate(\n    local_geary = local_c_perm(\n      x = log_trips,  # Use the transformed variable\n      nb = nb,\n      wt = wt, \n      nsim = 999 \n    )\n  )\n\nlocal_geary_data <- local_geary_results %>%\n  select(HEX_ID, total_trips, log_trips, local_geary) %>%  \n  tidyr::unnest(local_geary)\n\nglimpse(local_geary_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 799\nColumns: 14\n$ HEX_ID       <fct> H0001, H0002, H0003, H0004, H0005, H0006, H0007, H0008, H…\n$ total_trips  <dbl> 4144, 960, 2708, 7645, 1060, 831, 3303, 1020, 28032, 1077…\n$ log_trips    <dbl> 8.329658, 6.867974, 7.904335, 8.941938, 6.966967, 6.72383…\n$ ci           <dbl> 0.05486961, 0.59006254, 0.35199149, 0.77017559, 0.8830639…\n$ cluster      <fct> Low-Low, Low-Low, Low-Low, Low-Low, Low-Low, Low-Low, Low…\n$ e_ci         <dbl> 2.852021, 5.847704, 3.505028, 2.092000, 5.440620, 6.14061…\n$ var_ci       <dbl> 5.2034337, 4.8382473, 2.4720866, 0.8313132, 3.3662129, 4.…\n$ z_ci         <dbl> -1.2262272, -2.3902697, -2.0053821, -1.4497439, -2.484055…\n$ p_ci         <dbl> 0.220113170, 0.016836003, 0.044922211, 0.147129960, 0.012…\n$ p_ci_sim     <dbl> 0.152, 0.012, 0.022, 0.130, 0.008, 0.008, 0.004, 0.032, 0…\n$ p_folded_sim <dbl> 0.076, 0.006, 0.011, 0.065, 0.004, 0.004, 0.002, 0.016, 0…\n$ skewness     <dbl> 0.64337273, 0.15655371, 0.38155551, 0.44772271, 0.0325667…\n$ kurtosis     <dbl> 0.097325202, -0.054463226, 0.246394845, 0.426286178, -0.4…\n$ geometry     <POLYGON [m]> POLYGON ((4167.538 27510.65..., POLYGON ((4167.53…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlocal_geary_data <- local_geary_data %>%\n  filter(HEX_ID %in% hexagon_trips$HEX_ID)\n\ncat(\"local_geary_data now has:\", nrow(local_geary_data), \"hexagons\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlocal_geary_data now has: 799 hexagons\n```\n\n\n:::\n:::\n\n\n#### 3.4.2 Visualising Local Geary's C Values and clusters\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create Geary_Cluster column\nlocal_geary_data <- local_geary_data %>%\n  mutate(\n    Geary_Cluster = case_when(\n      p_ci >= 0.05 ~ \"Insignificant\",\n      ci < 1 & cluster == \"High-High\" ~ \"High-High Similarity\",\n      ci < 1 & cluster == \"Low-Low\" ~ \"Low-Low Similarity\", \n      ci > 1 & cluster == \"High-Low\" ~ \"High-Low Dissimilarity\",\n      ci > 1 & cluster == \"Low-High\" ~ \"Low-High Dissimilarity\",\n      TRUE ~ \"Insignificant\"\n    ),\n    # Convert to factor for consistent ordering\n    Geary_Cluster = factor(\n      Geary_Cluster,\n      levels = c(\n        \"High-High Similarity\",\n        \"Low-Low Similarity\",\n        \"High-Low Dissimilarity\", \n        \"Low-High Dissimilarity\",\n        \"Insignificant\"\n      )\n    ),\n    # Create strength classification for significant values\n    geary_strength = case_when(\n      p_ci >= 0.05 ~ \"Not Significant\",\n      ci < 0.5 ~ \"Strong Positive Similarity\",\n      ci >= 0.5 & ci < 1 ~ \"Weak Positive Similarity\",\n      ci >= 1 & ci < 1.5 ~ \"Weak Negative Similarity\", \n      ci >= 1.5 ~ \"Strong Negative Similarity\",\n      TRUE ~ \"Not Significant\"\n    ),\n    geary_strength = factor(\n      geary_strength,\n      levels = c(\n        \"Strong Positive Similarity\",\n        \"Weak Positive Similarity\",\n        \"Weak Negative Similarity\",\n        \"Strong Negative Similarity\",\n        \"Not Significant\"\n      )\n    )\n  )\n\n# Map 1: Geary's C Strength values\ngeary_strength_map <- tm_shape(local_geary_data) +\n  tm_polygons(\n    fill = \"geary_strength\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"Strong Positive Similarity\" = \"#2166ac\",\n        \"Weak Positive Similarity\" = \"#67a9cf\",\n        \"Weak Negative Similarity\" = \"#fddbc7\", \n        \"Strong Negative Similarity\" = \"#d6604d\",\n        \"Not Significant\" = \"grey80\"\n      )\n    ),\n    fill.legend = tm_legend(title = \"Geary's C Strength\")\n  ) +\n  tm_borders(col = \"black\", fill_alpha = 0.3) +\n  tm_title(\"Local Geary's C Strength (p < 0.05)\")\n\n# Map 2: Geary Clusters (custom classification)\ngeary_clusters_map <- tm_shape(local_geary_data) +\n  tm_polygons(\n    fill = \"Geary_Cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"High-High Similarity\" = \"lightblue\",\n        \"Low-Low Similarity\" = \"pink\",  \n        \"High-Low Dissimilarity\" = \"blue\",\n        \"Low-High Dissimilarity\" = \"red\",\n        \"Insignificant\" = \"grey80\"\n      )\n    ),\n    fill.legend = tm_legend(title = \"Geary Similarity Clusters\")\n  ) +\n  tm_borders(col = \"black\", fill_alpha = 0.3) +\n  tm_title(\"Local Geary's C Similarity Patterns\")\n\n# Arrange maps side by side\ntmap_arrange(geary_strength_map, geary_clusters_map, \n             ncol = 2, \n             heights = c(1, 1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nFrom the visualisations of Local Geary's C values, we can see that the bus ridership on the West and North exhibits **strong positive similarity** (dark blue shades), where majority of hexagons have *total_trips* similar to their neighbours (i.e. Low-Low or High-High clustering). Whereas in the South and Northeast, there exists some areas of **strong negative similarity** (dark orange shades). \n\nA closer look at the Geary clusters show that the West and North areas exhibit Low-High dissimilarity (pink shades), which means that there are cold spots in these areas.\n\n### 3.5 Computing Getis-Ord Gi* \n\nTo identify localised spatial clusters of extreme values (hot spots and cold spots), we compute the Getis-Ord Gi* statistic. This is achieved using the `st_local_g()` function from the **sfdep** package. The resulting Gi* value provides a measure of similarity (clustering), specifically comparing a hexagon's value to its neighbours, including itself. \n\nIts interpretation is as such:\n\n-   A positive and large Gi* value indicates positive autocorrelation (High-High clustering/Hot Spot).\n-   A negative and large Gi* value indicates positive autocorrelation (Low-Low clustering/Cold Spot).\n-   A Gi* value near 0 indicates no spatial autocorrelation; the values are randomly distributed.\n\nWe will use the associated p-values and the Z-scores derived from Gi* to generate a final map that visually pinpoints the statistically significant hot spots and cold spots of bus ridership.\n\n#### 3.5.1 Computing distance weight matrix\n\nGetis-Ord Gi* analysis defines neighbours based on distance, and there are 2 types of distance-based proximity matrices that can be utilised:\n\n-   fixed distance weight matrix,\n-   adaptive distance weight matrix\n\n##### 3.5.1.1 Computing adaptive distance weights\n\nFor bus ridership analysis in Singapore, fixed distance weights capture **natural variations** where dense hexagons have more neighbouring stops within a fixed radius, smoothing local relationships. \n\nIn contrast, adaptive distance weights ensure consistent analysis by maintaining the same number of neighbors (k-nearest) for each hexagon, providing **uniform spatial context** regardless of urban density, which helps isolate true ridership patterns from structural biases of the transport infrastructure.\n\nHence, we will use adaptive distance weights for Gi\\* analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_trips_adw <- hexagon_trips %>%\n  mutate(nb = include_self(\n    st_knn(\n      st_geometry(geometry),\n      k = 6)),\n    wt = st_weights(\n      nb, style = \"W\"),\n    .before = 1)\n```\n:::\n\n\n#### 3.5.2 Computing local Gi\\*\n\nLocal Gi* is a Getis-Ord statistic that identifies statistically significant hot spots (clusters of high values) and cold spots (clusters of low values) in spatial data. It calculates a Z-score and p-value for each location by comparing local neighborhood sums to the global average, determining whether observed spatial clustering occurs by random chance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_adw <- hexagon_trips_adw %>%\n  mutate(\n    gistar = local_gstar_perm(\n      total_trips, nb, wt, nsim = 99),\n    .before = 1) %>%\n  unnest(gistar)\n```\n:::\n\n\n#### 3.5.3 Preparing and Visualising HCSA Map\n\n##### 3.5.3.1  Mapping Gi\\* with adaptive distance weights\n\nThematic mapping functions of tmaps are used to prepare a choropleth map showing the distribution of Gi\\* values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create Gi* intervals\nHCSA_adw <- HCSA_adw %>%\n  mutate(\n    gi_strength = case_when(\n      p_value > 0.05 ~ \"Not Significant\",\n      gi_star >= 3 ~ \"Very Strong Hot Spot\",\n      gi_star >= 2 & gi_star < 3 ~ \"Strong Hot Spot\", \n      gi_star >= 1 & gi_star < 2 ~ \"Moderate Hot Spot\",\n      gi_star > 0 & gi_star < 1 ~ \"Weak Hot Spot\",\n      gi_star <= -3 ~ \"Very Strong Cold Spot\",\n      gi_star <= -2 & gi_star > -3 ~ \"Strong Cold Spot\",\n      gi_star <= -1 & gi_star > -2 ~ \"Moderate Cold Spot\",\n      gi_star < 0 & gi_star > -1 ~ \"Weak Cold Spot\",\n      TRUE ~ \"Not Significant\"\n    ),\n    # Convert to factor with fixed order\n    gi_strength = factor(\n      gi_strength,\n      levels = c(\n        \"Very Strong Hot Spot\",\n        \"Strong Hot Spot\", \n        \"Moderate Hot Spot\",\n        \"Weak Hot Spot\",\n        \"Weak Cold Spot\",\n        \"Moderate Cold Spot\",\n        \"Strong Cold Spot\",\n        \"Very Strong Cold Spot\",\n        \"Not Significant\"\n      )\n    )\n  )\n\n# Map with fixed legend order\ntm_shape(HCSA_adw) +\n  tm_polygons(\n    fill = \"gi_strength\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"Very Strong Hot Spot\" = \"#8B0000\",\n        \"Strong Hot Spot\" = \"#FF0000\", \n        \"Moderate Hot Spot\" = \"#FF6B6B\",\n        \"Weak Hot Spot\" = \"#FFB6C1\",\n        \"Very Strong Cold Spot\" = \"#00008B\",\n        \"Strong Cold Spot\" = \"#0000FF\",\n        \"Moderate Cold Spot\" = \"#6B8EFF\", \n        \"Weak Cold Spot\" = \"#B6C1FF\",\n        \"Not Significant\" = \"grey80\"\n      )\n    ),\n    fill.legend = tm_legend(title = \"Gi* Cluster Strength\")\n  ) +\n  tm_borders(col = \"grey\", alpha = 0.3) +\n  tm_title(\"Gi* Hot and Cold Spots by Intensity (p ≤ 0.05)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex2_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nFrom the visualisation map, we can see that there are statistically significant **Very Strong Hot Spots** in the West, North and East areas (Gi\\*>0). The Gi\\* values show that high bus ridership values in these regions is unlikely to occur by random chance (p < 0.05), representing genuine spatial patterns rather than random distributions.\n\n## 4 Emerging Hot Spot Analysis (EHSA)\n\n**Emerging Hot Spot Analysis (EHSA)** is a spatio-temporal technique that identifies how bus ridership clusters are changing across Singapore's hexagon grid over time. \n\nThe process works by first converting peak ridership data into a space-time cube. For each period, the Getis-Ord Gi\\* statistic identifies Hot and Cold Spots. The Mann-Kendall trend test is then applied to the sequence of these Gi\\* values for every hexagon to categorise areas of new/growing/persistent hot/cold spots, providing deeper insight for bus demand planning.\n\n### 4.1 Check Trips per Peak Period Dataset\n\nBefore creating a Space-Time cube, we will check to ensure every hexagon has data for all time periods and that there are no duplicate location-time combinations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# See the distribution of time periods per location\ntime_counts <- hexagon_trips_peak %>%\n  count(HEX_ID) %>%\n  arrange(n)\n\ncat(\"Time periods per location:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime periods per location:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(table(time_counts$n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  2   3   4 \n  6   1 792 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Get the total number of unique time periods\nn_time_periods <- length(unique(hexagon_trips_peak$Peak_Period))\ncat(\"Total number of time periods:\", n_time_periods, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal number of time periods: 4 \n```\n\n\n:::\n\n```{.r .cell-code}\n# See which locations are missing time periods\nlocations_with_all_periods <- hexagon_trips_peak %>%\n  count(HEX_ID) %>%\n  filter(n == n_time_periods) %>%\n  pull(HEX_ID)\n\ncat(\"Locations with all time periods:\", length(locations_with_all_periods), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLocations with all time periods: 792 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Locations missing some time periods:\", nrow(time_counts) - length(locations_with_all_periods), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLocations missing some time periods: 7 \n```\n\n\n:::\n:::\n\n\nThere are 7 hexagons missing some time periods, hence we will filter to only hexagons with all time periods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_trips_peak_filtered <- hexagon_trips_peak %>%\n  filter(HEX_ID %in% locations_with_all_periods)\n```\n:::\n\n\n### 4.1 Creating a Time Series Cube\n\nWe use `spacetime()` of **sfdep** package to create an spatio-temporal cube, and verify its object type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_trips_peak_st <- sfdep::as_spacetime(\n  hexagon_trips_peak_filtered,\n  \"HEX_ID\", \n  \"Peak_Period\"\n)\n\nis_spacetime_cube(hexagon_trips_peak_st)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Balanced spacetime cube with\", nrow(hexagon_trips_peak_st), \"rows\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalanced spacetime cube with 3168 rows\n```\n\n\n:::\n:::\n\n\n### 4.2 \n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(hexagon_trips_peak)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 3 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 3792.538 ymin: 27510.65 xmax: 4542.538 ymax: 30974.75\nProjected CRS: SVY21 / Singapore TM\n  HEX_ID            Peak_Period total_trips                       geometry\n1  H0001               Off-Peak        1360 POLYGON ((4167.538 27510.65...\n2  H0001 Weekday Afternoon Peak        1111 POLYGON ((4167.538 27510.65...\n3  H0001   Weekday Morning Peak         374 POLYGON ((4167.538 27510.65...\n4  H0001   Weekend/Holiday Peak        1299 POLYGON ((4167.538 27510.65...\n5  H0002               Off-Peak         467 POLYGON ((4167.538 30108.73...\n6  H0002 Weekday Afternoon Peak         234 POLYGON ((4167.538 30108.73...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "Take-home_Ex2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}