project:
  type: website

website:
  title: "ISSS626"
  navbar:
    left:
      - text: "Hands-on Exercise"
      - menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on Exercise/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on Exercise/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on Exercise/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on Exercise/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on Exercise/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on Exercise/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8"
          href: "Hands-on Exercise/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 9"
          href: "Hands-on Exercise/Hands-on_Ex09/Hands-on_Ex09.html"
        - text: "Hands-on Exercise 10"
          href: "Hands-on Exercise/Hands-on_Ex10/Hands-on_Ex10.html"
        - text: "Hands-on Exercise 11"
          href: "Hands-on Exercise/Hands-on_Ex11/Hands-on_Ex11.html"
        - text: "Hands-on Exercise 12"
          href: "Hands-on Exercise/Hands-on_Ex12/Hands-on_Ex12.html"
        - text: "Hands-on Exercise 13"
          href: "Hands-on Exercise/Hands-on_Ex13/Hands-on_Ex13.html"
      - text: "In-class Exercise"
      - menu: 
        - text: "In-class Exercise 1"
          href: "In-class Exercise/In-class_Ex01/In-class_Ex01.html"
        - text: "In-class Exercise 2" 
          href: "In-class Exercise/In-class_Ex02/In-class_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
    toc: true

editor: visual

