{
  "hash": "0326509577c8e94e60e7edc0013f2c0a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"8: Geographically Weighted Predictive Modelling\"\nauthor: \"Emma Chew En Chin\"\ndate: \"Oct 20, 2025\"\ndate-modified: \"last-modified\"\nformat: html\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n## 1 Overview\n\n**Geospatial predictive modeling** operates on the principle that event occurrences are not random or uniform in space. It uses geographically referenced data to describe how geospatial factors (like infrastructure, topography, or sociocultural elements) constrain and influence where events occur. The models achieve this by spatially correlating historical event locations with environmental factors that represent these constraints.\n\n## 2 The Datasets\n\n**Aspatial dataset:**\n\n-   HDB Resale data: a list of HDB resale transacted prices in Singapore from Jan 2017 onwards.\n\n**Geospatial dataset:**\n\n-   MP14_SUBZONE_WEB_PL: a polygon feature data providing information of URA 2014 Master Plan Planning Subzone boundary data. It is in ESRI shapefile format.\n\n-   Locational factors with geographic coordinates:\n\n    -   *Eldercare* data is a list of eldercare in Singapore. It is in shapefile format.\n    -   *Hawker Centre* data is a list of hawker centres in Singapore. It is in geojson format.\n    -   *Parks* data is a list of parks in Singapore. It is in geojson format.\n    -   *Supermarket* data is a list of supermarkets in Singapore. It is in geojson format.\n    -   *CHAS clinics* data is a list of CHAS clinics in Singapore. It is in geojson format.\n    -   *Childcare service* data is a list of childcare services in Singapore. It is in geojson format.\n    -   *Kindergartens* data is a list of kindergartens in Singapore. It is in geojson format.\n    -   *MRT* data is a list of MRT/LRT stations in Singapore with the station names and codes. It is in shapefile format.\n    -   *Bus stops* data is a list of bus stops in Singapore. It is in shapefile format.\n\n**Locational factors without geographic coordinates:**\n\n-   *Primary school* data is extracted from the list on General information of schools from data.gov portal. It is in csv format.\n\n**Retrieved/Scraped from other sources**\n\n-   *CBD coordinates* obtained from Google.\n-   *Shopping malls* data is a list of Shopping malls in Singapore obtained from Wikipedia.\n-   *Good primary schools* is a list of primary schools that are ordered in ranking in terms of popularity and this can be found at Local Salary Forum.\n\n## 3 Installing and Loading R packages\n\nThe following new packages will be used:\n\n-   `SpatialML`:Used for spatial machine learning and predictive modeling, often providing spatial extensions to common machine learning algorithms.\n-   `rsample`: Used for creating data splits and resamples (e.g., cross-validation, bootstrapping) for proper training, testing, and evaluation of predictive models.\n-   `metrics`: Provides various performance metrics (like RMSE, MAE, R-squared) to evaluate and compare the accuracy of predictive and machine learning models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, GWmodel, SpatialML, \n               tmap, rsample, Metrics, tidyverse)\n```\n:::\n\n\n## 4 Data Preparation\n\n### 4.1 Reading data from rds file\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdata <- read_rds(\"data/rawdata/mdata.rds\")\n```\n:::\n\n\n### 4.2 Data Sampling\n\nThe entire data is split into training and test data sets, 65% and 35% respectively, by using `initial_split()` of **rsample** package.\n\n**rsample** is one of the package of tidymodels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nresale_split <- initial_split(mdata, \n                              prop = 6.5/10,)\ntrain_data <- training(resale_split)\ntest_data <- testing(resale_split)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(train_data, \"data/model/train_data.rds\")\nwrite_rds(test_data, \"data/model/test_data.rds\")\n```\n:::\n\n\n## 5 Computing Correlation Matrix\n\nBefore we load the predictors into a predictive model, we will use a correlation matrix to examine if there is sign of multicollinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdata_nogeo <- mdata %>%\n  st_drop_geometry()\ncorrplot::corrplot(cor(mdata_nogeo[, 2:17]), \n                   diag = FALSE, \n                   order = \"AOE\",\n                   tl.pos = \"td\", \n                   tl.cex = 0.5, \n                   method = \"number\", \n                   type = \"upper\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex8_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nFrom the matrix, we can observe that all the correlation values are below 0.8, hence there is no sign of multicollinearity.\n\n## 6 Building a non-spatial multiple linear regression\n\nFirst, we retrieve the train and test datasets\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data <- read_rds(\"data/model/train_data.rds\")\ntest_data <- read_rds(\"data/model/test_data.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_mlr <- lm(resale_price ~ floor_area_sqm +\n                  storey_order + remaining_lease_mths +\n                  PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +\n                  PROX_MRT + PROX_PARK + PROX_MALL + \n                  PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n                  WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +\n                  WITHIN_1KM_PRISCH,\n                data=train_data)\nsummary(price_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm + storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER + PROX_MRT + PROX_PARK + \n    PROX_MALL + PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN + \n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n    data = train_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205193  -39120   -1930   36545  472355 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              107601.073  10601.261  10.150  < 2e-16 ***\nfloor_area_sqm             2780.698     90.579  30.699  < 2e-16 ***\nstorey_order              14299.298    339.115  42.167  < 2e-16 ***\nremaining_lease_mths        344.490      4.592  75.027  < 2e-16 ***\nPROX_CBD                 -16930.196    201.254 -84.124  < 2e-16 ***\nPROX_ELDERLYCARE         -14441.025    994.867 -14.516  < 2e-16 ***\nPROX_HAWKER              -19265.648   1273.597 -15.127  < 2e-16 ***\nPROX_MRT                 -32564.272   1744.232 -18.670  < 2e-16 ***\nPROX_PARK                 -5712.625   1483.885  -3.850 0.000119 ***\nPROX_MALL                -14717.388   2007.818  -7.330 2.47e-13 ***\nPROX_SUPERMARKET         -26881.938   4189.624  -6.416 1.46e-10 ***\nWITHIN_350M_KINDERGARTEN   8520.472    632.812  13.464  < 2e-16 ***\nWITHIN_350M_CHILDCARE     -4510.650    354.015 -12.741  < 2e-16 ***\nWITHIN_350M_BUS             813.493    222.574   3.655 0.000259 ***\nWITHIN_1KM_PRISCH         -8010.834    491.512 -16.298  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 61650 on 10320 degrees of freedom\nMultiple R-squared:  0.7373,\tAdjusted R-squared:  0.737 \nF-statistic:  2069 on 14 and 10320 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe adjusted R-squared of the model is 0.737, indicating that 73.73% of the variability in the resale price can be explained by the independent variables in the model.\n\nThe Residual Standard Error (RSE) is 61,650, which suggests that the typical or average difference between the model's predicted resale price and the actual resale price is approximately \\$61,650.\n\nThe p-value is \\< 0.05, indicating that the model is statistically significant, meaning the predictors collectively contribute significantly to predicting the resale price.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(price_mlr, \"data/model/price_mlr.rds\" ) \n```\n:::\n\n\n## 7 gwr Predictive Method\n\nWe will calibrate a model to predict HDB resale price by using geographically weighted regression method of the **GWmodel** package.\n\n### 7.1 Computing adaptive bandwidth\n\nFirstly, `bw.gwr()` of **GWmodel** package will be used to determine the optimal bandwidth to be used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths +\n    PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +\n    WITHIN_1KM_PRISCH,\n  data=train_data,\n  approach=\"CV\",\n  kernel=\"gaussian\",\n  adaptive=TRUE,\n  longlat=FALSE)\n\nwrite_rds(bw_adaptive, \"data/model/bw_adaptive.rds\")\n```\n:::\n\n\nThe result shows that 40 neighbour points will be the optimal bandwidth to be used if adaptive bandwidth is used for this data set.\n\nNote that this is a computational intensity and time consuming process. It is wiser to save the output as an rds file for future used without having to re-run the process again.\n\n### 7.2 Constructing the adaptive bandwidth gwr model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- read_rds(\n  \"data/model/bw_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- gwr.basic(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + \n    PROX_HAWKER + PROX_MRT + PROX_PARK + \n    PROX_MALL + PROX_SUPERMARKET +\n    WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH,\n  data=train_data,\n  bw=bw_adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE,\n  longlat = FALSE)\n\nwrite_rds(gwr_adaptive, \n          \"data/model/gwr_adaptive.rds\")\n```\n:::\n\n\nNote that this is a computational intensity and time consuming process. It is wiser to save the output as an rds file for future used without having to re-run the process again.\n\n### 7.3 Retrieve gwr output object\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- read_rds(\"data/model/gwr_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-10-25 12:41:09.814312 \n   Call:\n   gwr.basic(formula = resale_price ~ floor_area_sqm + storey_order + \n    remaining_lease_mths + PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER + \n    PROX_MRT + PROX_PARK + PROX_MALL + PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN + \n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n    data = train_data, bw = bw_adaptive, kernel = \"gaussian\", \n    adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm storey_order remaining_lease_mths PROX_CBD PROX_ELDERLYCARE PROX_HAWKER PROX_MRT PROX_PARK PROX_MALL PROX_SUPERMARKET WITHIN_350M_KINDERGARTEN WITHIN_350M_CHILDCARE WITHIN_350M_BUS WITHIN_1KM_PRISCH\n   Number of data points: 10335\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-205193  -39120   -1930   36545  472355 \n\n   Coefficients:\n                              Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)              107601.073  10601.261  10.150  < 2e-16 ***\n   floor_area_sqm             2780.698     90.579  30.699  < 2e-16 ***\n   storey_order              14299.298    339.115  42.167  < 2e-16 ***\n   remaining_lease_mths        344.490      4.592  75.027  < 2e-16 ***\n   PROX_CBD                 -16930.196    201.254 -84.124  < 2e-16 ***\n   PROX_ELDERLYCARE         -14441.025    994.867 -14.516  < 2e-16 ***\n   PROX_HAWKER              -19265.648   1273.597 -15.127  < 2e-16 ***\n   PROX_MRT                 -32564.272   1744.232 -18.670  < 2e-16 ***\n   PROX_PARK                 -5712.625   1483.885  -3.850 0.000119 ***\n   PROX_MALL                -14717.388   2007.818  -7.330 2.47e-13 ***\n   PROX_SUPERMARKET         -26881.938   4189.624  -6.416 1.46e-10 ***\n   WITHIN_350M_KINDERGARTEN   8520.472    632.812  13.464  < 2e-16 ***\n   WITHIN_350M_CHILDCARE     -4510.650    354.015 -12.741  < 2e-16 ***\n   WITHIN_350M_BUS             813.493    222.574   3.655 0.000259 ***\n   WITHIN_1KM_PRISCH         -8010.834    491.512 -16.298  < 2e-16 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 61650 on 10320 degrees of freedom\n   Multiple R-squared: 0.7373\n   Adjusted R-squared: 0.737 \n   F-statistic:  2069 on 14 and 10320 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 3.922202e+13\n   Sigma(hat): 61610.08\n   AIC:  257320.2\n   AICc:  257320.3\n   BIC:  247249\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 40 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                   Min.     1st Qu.      Median     3rd Qu.\n   Intercept                -3.2111e+08 -4.7727e+05 -8.3004e+03  5.5025e+05\n   floor_area_sqm           -2.8714e+04  1.4475e+03  2.3011e+03  3.3900e+03\n   storey_order              3.3186e+03  8.5899e+03  1.0826e+04  1.3397e+04\n   remaining_lease_mths     -1.4431e+03  2.6063e+02  3.9048e+02  5.2865e+02\n   PROX_CBD                 -1.0837e+07 -5.7697e+04 -1.3787e+04  2.6552e+04\n   PROX_ELDERLYCARE         -3.1896e+07 -4.0643e+04  1.0562e+04  6.1054e+04\n   PROX_HAWKER              -2.3985e+08 -5.1365e+04  3.0026e+03  6.4287e+04\n   PROX_MRT                 -1.1544e+07 -1.0488e+05 -4.9373e+04  5.1037e+03\n   PROX_PARK                -6.5961e+06 -4.8671e+04 -8.8128e+02  5.3498e+04\n   PROX_MALL                -1.8113e+07 -7.4238e+04 -1.3982e+04  4.9779e+04\n   PROX_SUPERMARKET         -4.5761e+06 -6.3461e+04 -1.7429e+04  3.5616e+04\n   WITHIN_350M_KINDERGARTEN -4.1638e+05 -6.0040e+03  9.0209e+01  4.7127e+03\n   WITHIN_350M_CHILDCARE    -1.0273e+05 -2.2375e+03  2.6668e+02  2.6388e+03\n   WITHIN_350M_BUS          -1.1757e+05 -1.4719e+03  1.1626e+02  1.7584e+03\n   WITHIN_1KM_PRISCH        -6.6465e+05 -5.5959e+03  2.6916e+02  5.7500e+03\n                                  Max.\n   Intercept                1.6493e+08\n   floor_area_sqm           5.0908e+04\n   storey_order             2.9537e+04\n   remaining_lease_mths     1.8119e+03\n   PROX_CBD                 2.2166e+07\n   PROX_ELDERLYCARE         8.2445e+07\n   PROX_HAWKER              5.9654e+06\n   PROX_MRT                 2.0189e+08\n   PROX_PARK                1.5072e+07\n   PROX_MALL                1.0443e+07\n   PROX_SUPERMARKET         3.8330e+06\n   WITHIN_350M_KINDERGARTEN 6.6799e+05\n   WITHIN_350M_CHILDCARE    1.0802e+05\n   WITHIN_350M_BUS          3.7313e+04\n   WITHIN_1KM_PRISCH        5.0133e+05\n   ************************Diagnostic information*************************\n   Number of data points: 10335 \n   Effective number of parameters (2trace(S) - trace(S'S)): 1730.101 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 8604.899 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 238871.8 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 237036.9 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 238209 \n   Residual sum of squares: 4.829176e+12 \n   R-square value:  0.9676571 \n   Adjusted R-square value:  0.9611535 \n\n   ***********************************************************************\n   Program stops at: 2025-10-25 12:43:19.493141 \n```\n\n\n:::\n:::\n\n\n### 7.4 Computing adaptive bandwidth for the test data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_bw_test_adaptive <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths +\n    PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +\n    WITHIN_1KM_PRISCH,\n  data=test_data,\n  approach=\"CV\",\n  kernel=\"gaussian\",\n  adaptive=TRUE,\n  longlat=FALSE)\n\nwrite_rds(gwr_bw_test_adaptive, \n          \"data/model/gwr_bw_test_adaptive.rds\")\n```\n:::\n\n\n### 7.5 Computing predicted values of the test data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data <- read_rds(\"data/model/train_data.rds\")\ntest_data <- read_rds(\"data/model/test_data.rds\")\n\ntrain_sp <- as_Spatial(train_data)\ntest_sp  <- as_Spatial(test_data)\n\ngwr_pred <- gwr.predict(\n  formula = resale_price ~ floor_area_sqm + \n    storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER + \n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + \n    WITHIN_1KM_PRISCH, \n  data = train_sp,          \n  predictdata = test_sp,    \n  bw = 40, \n  kernel = 'gaussian', \n  adaptive = TRUE, \n  longlat = FALSE)\n\nwrite_rds(gwr_pred, \n          \"data/model/gwr_pred.rds\")\n```\n:::\n\n\n## 8 Calibrating Random Forest Model\n\nWe will calibrate a model to predict HDB resale price by using `random forest` function of **ranger** package.\n\n### 8.1 Preparing coordinates data\n\nWe extract the x,y coordinates of the full, training and test data sets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(mdata)\ncoords_train <- st_coordinates(train_data)\ncoords_test <- st_coordinates(test_data)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords_train <- write_rds(\n  coords_train, \n  \"data/model/coords_train.rds\" )\ncoords_test <- write_rds(\n  coords_test, \n  \"data/model/coords_test.rds\" )\n```\n:::\n\n\n### 8.2 Dropping geometry field\n\nFirst, we will drop geometry column of the sf data.frame by using `st_drop_geometry()` of **sf** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data_nogeom <- train_data %>% \n  st_drop_geometry()\n\ntest_data_nogeom <- test_data %>% \n  st_drop_geometry()\n```\n:::\n\n\n### 8.3 Calibrating a non-spatial random forest model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nrf <- ranger(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + \n    PROX_HAWKER + PROX_MRT + PROX_PARK + \n    PROX_MALL + PROX_SUPERMARKET +\n    WITHIN_350M_KINDERGARTEN + \n    WITHIN_350M_CHILDCARE + \n    WITHIN_350M_BUS +  \n    WITHIN_1KM_PRISCH,\n  data=train_data_nogeom)\nrf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRanger result\n\nCall:\n ranger(formula = resale_price ~ floor_area_sqm + storey_order +      remaining_lease_mths + PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +      PROX_MRT + PROX_PARK + PROX_MALL + PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +      WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + WITHIN_1KM_PRISCH,      data = train_data_nogeom) \n\nType:                             Regression \nNumber of trees:                  500 \nSample size:                      10335 \nNumber of independent variables:  14 \nMtry:                             3 \nTarget node size:                 5 \nVariable importance mode:         none \nSplitrule:                        variance \nOOB prediction error (MSE):       728602496 \nR squared (OOB):                  0.9495728 \n```\n\n\n:::\n:::\n\n\n## 9 Calibrating Geographical Weighted Random Forest Model\n\nWe will calibrate a model to predict HDB resale price by using `grf()` of **SpatialML** package.\n\n### 9.1 Calibrating using training data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngwRF_adaptive <- grf(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + \n    PROX_HAWKER + PROX_MRT + PROX_PARK + \n    PROX_MALL + PROX_SUPERMARKET +\n    WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH,\n  dframe=train_data_nogeom, \n  bw=40,\n  kernel=\"adaptive\",\n  coords = coords_train,\n  ntree = 50,  # Reduce number of trees\n  mtry = 4,     # Set mtry parameter\n  importance = \"impurity\")\n\nwrite_rds(gwRF_adaptive, \"data/model/gwRF_adaptive.rds\")\n```\n:::\n\n\n### 9.2 Predicting by using test data\n\n#### 9.2.1 Preparing the test data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwRF_adaptive <- read_rds(\"data/model/gwRF_adaptive.rds\")\n```\n:::\n\n\nWe combine the test data with its corresponding coordinates data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data_nogeom <- cbind(\n  test_data, coords_test) %>%\n  st_drop_geometry()\n```\n:::\n\n\n#### 9.2.2 Predicting with test data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwRF_pred <- predict.grf(gwRF_adaptive, \n                           test_data_nogeom, \n                           x.var.name=\"X\",\n                           y.var.name=\"Y\", \n                           local.w=1,\n                           global.w=0)\n\nGRF_pred <- write_rds(gwRF_pred, \"data/model/GRF_pred.rds\")\n```\n:::\n\n\n#### 9.2.3 Converting the predicting output into a data frame\n\nThe output of the `predict.grf()` is a vector of predicted values. It is wiser to convert it into a data frame for further visualisation and analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGRF_pred <- read_rds(\n  \"data/model/GRF_pred.rds\")\nGRF_pred_df <- as.data.frame(GRF_pred)\n```\n:::\n\n\n`cbind()` is used to append the predicted values onto *test_data*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data_p <- cbind(\n  test_data, GRF_pred_df) %>%\n  select(resale_price, GRF_pred)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(test_data_p, \n          \"data/model/test_data_p.rds\")\n```\n:::\n\n\n### 9.3 Calculating Root Mean Square Error\n\nThe root mean square error (RMSE) allows us to measure how far predicted values are from observed values in a regression analysis. In the code chunk below, rmse() of Metrics package is used to compute the RMSE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse(test_data_p$resale_price, \n     test_data_p$GRF_pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28413.83\n```\n\n\n:::\n:::\n\n\n### 9.4 Visualising the predicted values\n\nScatterplot can be used to visualise the actual resale price and the predicted resale price.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = test_data_p,\n       aes(x = GRF_pred,\n           y = resale_price)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex8_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "Hands-on_Ex8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}