{
  "hash": "655a2dff82fcab33ffeda0d889152bd7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3: Modelling HDB Resale Prices with Geographically Weighted Methods\"\nauthor: \"Emma Chew En Chin\"\ndate: \"Oct 26, 2025\"\ndate-modified: \"last-modified\"\nformat: html\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n## 1 Overview\n\nIn Singapore, understanding the factors that influence the potential prices of HDB resale flats is crucial. For prospective homeowners, this knowledge is vital as it directly impacts the long-term financial sustainability of the purchase, including the amount of housing equity they can secure and how well the flat retains its value over time. This understanding allows buyers to make informed and prudent housing decisions regarding the flat size and location that best meet their family's needs and financial standing.\n\nThis study utilises **Geographically Weighted Models (GWMs)** to build a price prediction model to analyse the key factors that influence HDB resale prices, specifically for **4-room flats** due to its popularity with young families. From this, we can produce local coefficients for each data point (or small region), reflecting the spatial heterogeneity in the data. The data period for analysis will be 1 January 2025 to 30 September 2025.\n\n## 2 Installing and Loading R packages\n\n::: callout-note\n**Data Acquisition & Handling**\n\n-   `httr`: Makes HTTP requests to APIs; used for url call from OneMap.\n-   `jsonlite`: Parses JSON data returned from web APIs into usable R data frames.\n-   `rvest`: For scraping of data from web pages.\n-   `tidyverse`: A meta-package for data manipulation (dplyr), visualization (ggplot2), and more. The core toolkit for data wrangling.\n\n**Geospatial Core**\n\n-   `sf`: Handles spatial data (points, polygons). Used for spatial joins, distance calculations, and mapping.\n-   `tmap`: Creates thematic maps (chloropleth, point maps) to visualise spatial patterns in prices and model results.\n\n**Geospatial Modelling & Analysis**\n\n-   `spdep`: Provides spatial dependence tests (e.g., Moran's I for spatial autocorrelation) and classic spatial econometric models.\n-   `GWmodel`: The primary package for GWR and multiscale GWR. Fits models where coefficients vary geographically.\n-   `SpatialML`: Provides geographically weighted random forests (gwrf()), blending random forests with local modeling.\n-   `spatialRF`: Provides spatial random forest models and spatial cross-validation techniques for improved spatial prediction.\n\n**Model Pipeline and Evaluation**\n\n-   `rsample`: Creates training/test splits for model validation using techniques like cross-validation.\n-   `Metrics`: Calculates model performance metrics (RMSE, MAE, R²) to evaluate prediction accuracy.\n-   `randomForestExplainer`: Provides tools for interpreting and explaining random forest models, including variable importance and interaction effects.\n\n**Reporting & Visualisation**\n\n-   `knitr`: Dynamic report generation and reproducible research; integrates R code with documentation.\n-   `kableExtra`: Enhances table formatting and styling in R Markdown documents and Shiny applications.\n\n**Utility**\n\n-   `progress`: Adds progress bars to loops and long-running operations, improving user experience during spatial computations.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(httr, sf, tmap, jsonlite, progress,\n               spdep, GWmodel, SpatialML, \n               tmap, rsample, Metrics, tidyverse, rvest,\n               knitr, kableExtra, spatialRF,\n               randomForestExplainer)\n```\n:::\n\n\n## 3 Data Preparation\n\n### 3.1 The Datasets\n\n::: callout-note\n**Aspatial dataset:**\n\n-   HDB Resale data: a list of HDB resale transacted prices in Singapore from Jan 2017 onwards.\n\n**Geospatial dataset:**\n\n-   MP14_SUBZONE_WEB_PL: a polygon feature data providing information of URA 2014 Master Plan Planning Subzone boundary data. It is in ESRI shapefile format.\n\n-   Transport Factors:\n\n    -   *MRT* data is a list of MRT/LRT stations in Singapore with the station names and codes. It is in geojson format.\n    -   *Bus stops* data is a list of bus stops in Singapore. It is in geojson format.\n\n-   Education Factors:\n\n    -   *Preschool* data is a list of preschools in Singapore. It is in geojson format.\n    -   *Childcare service* data is a list of childcare services in Singapore. It is in geojson format.\n    -   *School* data is a list of primary, secondary, junior colleges schools in Singapore. It is in csv format.\n\n-   Elderly-care Factors:\n\n    -   *Eldercare* data is a list of eldercare in Singapore. It is in geojson format.\n\n-   Recreational Factors\n\n    -   *Parks* data is a list of parks in Singapore. It is in geojson format.\n    -   *Community clubs* data is a list of community clubs in Singapore. It is in geojson format.\n    -   *Sports Facilities* data is a list of public sports facilities in Singapore. It is in geojson format.\n    -   *GymsSG* data is a list of public gym facilities in Singapore. It is in geojson format.\n\n-   Food Factors\n\n    -   *Hawker Centre* data is a list of hawker centres in Singapore. It is in geojson format.\n    -   *Supermarket* data is a list of supermarkets in Singapore. It is in geojson format.\n\n-   Healthcare Factors\n\n    -   *CHAS clinics* data is a list of CHAS clinics in Singapore. It is in geojson format.\n:::\n\n### 3.2 Importing Shapefile Polygon data\n\nShapefile Polygon data, mpsz, is imported for visual checks for geospatial data to ascertain the following:\n\n-   **Spatial coverage validation:** To verify all points fall within expected boundaries\n-   **Coordinate system alignment:** To ensure that both layers use the same CRS\n-   **Spatial distribution patterns:** To quickly identify clusters, gaps or unusual patterns\n-   **Data completeness verification:** To find missing or outlier points\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = st_read(dsn = \"data/geospatial\", \n               layer = \"MP14_SUBZONE_WEB_PL\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_kml_field <- function(html_text, field_name) {\n  if (is.na(html_text) || html_text == \"\") return(NA_character_)\n  \n  page <- read_html(html_text)\n  rows <- page %>% html_elements(\"tr\")\n  \n  value <- rows %>%\n    keep(~ html_text2(html_element(.x, \"th\")) == field_name) %>%\n    html_element(\"td\") %>%\n    html_text2()\n  \n  if (length(value) == 0) NA_character_ else value\n}\n```\n:::\n\n\n### 3.2 Importing HDB Resale data\n\nNext, we import and clean the HDB resale dataset by using OneMap reverse geocoding to obtain the coordinates from the street addresses of the HDB flats.\n\nWe can reverse geocode the HDB postal code, as there is only blk number and street name in the Resale Flats dataset.\n\nThis is the documentation: [OneMap Reverse Geocoding](https://www.onemap.gov.sg/apidocs/reverseGeocode)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <-read_csv(\"data/rawdata/HDBresale.csv\") %>%\n  filter(flat_type == \"4 ROOM\") %>%\n  filter(month >= \"2025-01\" & month < \"2025-09\")\n\nglimpse(HDBresale)\n```\n:::\n\n\nChanging ST to SAINT so that it does not look like 'Street'.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$street_name <- gsub(\n  \"ST\\\\.\", \"SAINT\",\n  HDBresale$street_name)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeocode <- function(block, streetname) {\n  base_url <- \"https://onemap.gov.sg/api/common/elastic/search\"\n  address <- paste(block, streetname, sep = \" \")\n  query <- list(\"searchVal\" = address,\n                \"returnGeom\" = \"Y\",\n                \"getAddrDetails\" = \"N\",\n                \"pageNum\" = \"1\")\n  \n  res <-GET(base_url, query = query)\n  restext <- content(res, as=\"text\")\n  \n  output <- fromJSON(restext) %>%\n    as.data.frame %>%\n    select(results.LATITUDE, results.LONGITUDE)\n  \n  return(output)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$LATITUDE <- 0\nHDBresale$LONGITUDE <- 0\n\nfor (i in 1:nrow(HDBresale)){\n  temp_output <- geocode(HDBresale[i, 4], HDBresale[i, 5])\n  \n  HDBresale$LATITUDE[i] <- temp_output$results.LATITUDE\n  HDBresale$LONGITUDE[i] <- temp_output$results.LONGITUDE\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDBresale)\n```\n:::\n\n\nSince HDBresale contains LATITUDE and LONGITUDE columns (which are in the WGS 84 geographic coordinate system, or EPSG:4326), we need to convert it into an sf (Simple Features) object and then transform it to the SVY21 (Singapore Projected Coordinate System, EPSG:3414).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale %>%\n  st_as_sf(\n    coords = c(\"LONGITUDE\", \"LATITUDE\"),\n    crs=4326) %>%\n  st_transform(crs = 3414)\n\nsaveRDS(HDBresale_sf, file = \"data/rds/HDBresale_sf.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- read_rds(\"data/rds/HDBresale_sf.rds\")\n```\n:::\n\n\nWe check if there are overlapping points in HDBresale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverlapping_points <- HDBresale_sf %>%\n  mutate(overlap = lengths(st_equals(., .)) > 1)\n```\n:::\n\n\nUsing `jitter()` to move point features away from each other by 1m to avoid overlapping points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale_sf %>%\n  st_jitter(amount = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz), col = NA, border = \"gray\", main = \"HDB Resale Locations\")\nplot(st_geometry(HDBresale_sf), add = TRUE, col = \"black\", pch = 16, cex = 0.1)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### 3.3 Importing Schools data\n\nAs Schools data is in address format, we also conduct the same reverse geocoding with OneMap API to obtain the coordinate data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschools <-read_csv(\"data/rawdata/Schools.csv\")\n```\n:::\n\n\nWe utilise the *postal_code* attribute in *schools* dataframe to retrieve the coordinates from OneMap API.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschools_postcodes <- unique(schools$postal_code)\n\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\n# Found: geocoded, Not found: cannot be geocoded (e.g.) New development area or inaccurate postal code\nfound <- data.frame()\nnot_found <- data.frame(postcode = character(), stringsAsFactors = FALSE)\n\nfor (pc in schools_postcodes) {\n  # Convert postal code to character for the API query\n  query <- list(\n    searchVal = as.character(pc),  # Convert to character here\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum = \"1\"\n  )\n  \n  res <- GET(url, query = query)\n  json <- content(res)\n  \n  if (json$found != 0) {\n    results <- bind_rows(lapply(json$results, as.data.frame))\n    results$input_postcode <- as.character(pc)  # Convert to character here too\n    found <- bind_rows(found, results)\n  } else {\n    not_found <- bind_rows(not_found, data.frame(postcode = as.character(pc), stringsAsFactors = FALSE))\n  }\n  Sys.sleep(0.1)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschools_clean <- schools %>%\n  filter(!postal_code %in% not_found$postcode)\n\ncat(\"Original schools rows:\", nrow(schools), \"\\n\")\ncat(\"Cleaned schools rows:\", nrow(schools_clean), \"\\n\")\ncat(\"Number of postal codes removed:\", nrow(schools) - nrow(schools_clean), \"\\n\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschools_joined <- schools_clean %>%\n  mutate(postal_code = as.character(postal_code)) %>%\n  left_join(\n    found %>%\n      group_by(input_postcode) %>%\n      slice(1) %>%  # Take the first geocoded result for each postal code\n      ungroup(),\n    by = c('postal_code' = 'input_postcode')\n  ) %>%\n  mutate(\n    LONGITUDE = as.numeric(LONGITUDE),  \n    LATITUDE = as.numeric(LATITUDE)\n  ) %>%\n  group_by(LONGITUDE, LATITUDE) %>%\n  mutate(\n    n_coords = n(),\n    jitter_applied = n_coords > 1 & !is.na(LONGITUDE) & !is.na(LATITUDE),\n    LONGITUDE = ifelse(jitter_applied, jitter(LONGITUDE), LONGITUDE),\n    LATITUDE = ifelse(jitter_applied, jitter(LATITUDE), LATITUDE)\n  ) %>%\n  ungroup() %>%\n  select(-n_coords)\n\nsaveRDS(schools_joined, file = \"data/rds/schools_joined.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschools_joined <- read_rds(\"data/rds/schools_joined.rds\")\n\nschools_sf <- schools_joined %>%\n  filter(!is.na(LONGITUDE) & !is.na(LATITUDE)) %>%\n  st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326)\n\n# Transform to same CRS as mpsz\nschools_sf <- st_transform(schools_sf, st_crs(mpsz))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz), col = NA, border = \"gray\", main = \"School Locations\")\nplot(st_geometry(schools_sf), add = TRUE, col = \"black\", pch = 16, cex = 0.1)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### 3.4 Importing MRT data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt <- st_read(\"data/geospatial/LTAMRTStationExitKML.kml\") %>%\n  st_transform(crs = 3414)\n\nsaveRDS(mrt, file = \"data/rds/mrt_data.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt_sf <- read_rds(\"data/rds/mrt_data.rds\")\n```\n:::\n\n\nMRT station names are extracted using a html function as below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_station_name <- function(html_text) {\n  if (is.na(html_text) || html_text == \"\") return(NA_character_)\n  \n  tryCatch({\n    page <- read_html(html_text)\n    # Find the row that contains STATION_NA\n    rows <- html_elements(page, \"tr\")\n    \n    for (row in rows) {\n      th_text <- html_text(html_element(row, \"th\"))\n      if (!is.na(th_text) && th_text == \"STATION_NA\") {\n        station_name <- html_text(html_element(row, \"td\"))\n        # Remove \" MRT STATION\" and \" STATION\" from the name\n        station_name <- gsub(\" MRT STATION$\", \"\", station_name)\n        station_name <- gsub(\" LRT STATION$\", \"\", station_name)\n        return(station_name)\n      }\n    }\n    return(NA_character_)\n  }, error = function(e) {\n    return(NA_character_)\n  })\n}\n```\n:::\n\n\nStation names are extracted and duplicates of station names are removed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Apply to extract station names\nmrt_sf$station_name <- sapply(mrt_sf$Description, extract_station_name)\n\nmrt_sf$station_name <- sapply(mrt_sf$Description, extract_station_name) %>%\n  toupper() %>%                    # Convert to uppercase\n  trimws() %>%                     # Remove leading/trailing spaces\n  gsub(\"[^A-Z0-9 ]\", \"\", .)       # Remove special characters\n\n# Remove duplicate stations\nmrt_clean <- mrt_sf %>%\n  distinct(station_name, .keep_all = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz), col = NA, border = \"gray\", main = \"MRT Locations\")\nplot(st_geometry(mrt_clean), add = TRUE, col = \"black\", pch = 16, cex = 0.1)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n### 3.5 Importing Transport data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BUSSTOP' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\LTABusStop.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 5166 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6174 ymin: 1.255769 xmax: 104.0156 ymax: 1.495439\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n### 3.6 Importing Education data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PreSchoolsLocation' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\PreSchoolsLocation.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CHILDCARE' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\ChildCareServices.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1925 features and 16 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n### 3.7 Importing Elderly Care data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `EldercareServices' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\EldercareServices.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 133 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.7119 ymin: 1.271472 xmax: 103.9561 ymax: 1.439561\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n### 3.8 Importing Recreational data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `NATIONALPARKS' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\Parks.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 450 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6929 ymin: 1.263958 xmax: 104.0538 ymax: 1.461944\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CommunityClubs' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\CommunityClubs.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 125 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6923 ymin: 1.274863 xmax: 103.9592 ymax: 1.459038\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SPORTSG_SPORT_FACILITIES' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\SportSGSportFacilitiesGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 45 features and 8 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6938 ymin: 1.276323 xmax: 103.9518 ymax: 1.448263\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `GymsSGGEOJSON' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\GymsSGGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 159 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6938 ymin: 1.262063 xmax: 103.9518 ymax: 1.435078\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n### 3.9 Importing Food data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SSOT_HAWKERCENTRES' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\HawkerCentresGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 129 features and 20 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6972 ymin: 1.272761 xmax: 103.9882 ymax: 1.448263\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SupermarketsGEOJSON' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\SupermarketsGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 526 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6258 ymin: 1.24715 xmax: 104.0036 ymax: 1.461526\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n### 3.10 Importing Healthcare data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CHASClinics' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Take-home Exercise\\Take-home_Ex3\\data\\geospatial\\CHASClinics.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1193 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.5818 ymin: 1.016264 xmax: 103.9903 ymax: 1.456037\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n## 4 Data Wrangling\n\n### 4.1 Creating Proximity and Count features\n\nWe will calculate 2 types of features for each HDB resale flat:\n\n-   **Proximity features:** Calculate distance to nearest amenity\n-   **Count features:** Count number of amenities within a range of radius\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalculate_custom_spatial_features <- function(hdb_sf, \n                                             amenities_list,\n                                             proximity_amenities = NULL,\n                                             count_amenities = NULL,\n                                             count_radii = c(350, 1000)) {\n  \n  # Use all amenities if none specified\n  if (is.null(proximity_amenities)) {\n    proximity_amenities <- names(amenities_list)\n  }\n  if (is.null(count_amenities)) {\n    count_amenities <- names(amenities_list)\n  }\n  \n  result <- hdb_sf\n  \n  # 1. CALCULATE PROXIMITY FEATURES\n  cat(\"Calculating proximity features...\\n\")\n  for (amenity_name in proximity_amenities) {\n    tryCatch({\n      amenity_sf <- amenities_list[[amenity_name]]\n      prox_col <- paste0(\"PROX_\", toupper(amenity_name))\n      \n      # Calculate distance to nearest feature\n      nearest_indices <- st_nearest_feature(result, amenity_sf)\n      distances <- st_distance(result, amenity_sf[nearest_indices, ], by_element = TRUE)\n      \n      result[[prox_col]] <- as.numeric(distances)\n      cat(\"  ✓\", prox_col, \"\\n\")\n      \n    }, error = function(e) {\n      cat(\"  ✗ Failed:\", amenity_name, \"-\", e$message, \"\\n\")\n      result[[paste0(\"PROX_\", toupper(amenity_name))]] <- NA_real_\n    })\n  }\n  \n  # 2. CALCULATE COUNT FEATURES\n  cat(\"Calculating count features...\\n\")\n  for (amenity_name in count_amenities) {\n    tryCatch({\n      amenity_sf <- amenities_list[[amenity_name]]\n      \n      for (radius in count_radii) {\n        count_col <- paste0(\"COUNT_\", radius, \"M_\", toupper(amenity_name))\n        \n        # Create buffers and count intersections\n        buffers <- st_buffer(result, radius)\n        counts <- lengths(st_intersects(buffers, amenity_sf))\n        \n        result[[count_col]] <- counts\n        cat(\"  ✓\", count_col, \"\\n\")\n      }\n      \n    }, error = function(e) {\n      cat(\"  ✗ Failed counts for:\", amenity_name, \"-\", e$message, \"\\n\")\n      for (radius in count_radii) {\n        result[[paste0(\"COUNT_\", radius, \"M_\", toupper(amenity_name))]] <- NA_real_\n      }\n    })\n  }\n  \n  return(result)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define your amenities \namenities <- list(\n  busstop_2 = busstop_clean,\n  childcare = childcare,\n  clinics = clinics,\n  clubs = clubs,\n  eldercare = eldercare,\n  gyms = gyms,\n  hawkers = hawkers,\n  mrt_2 = mrt_clean,\n  parks = parks,\n  preschool = preschool,\n  schools_2 = schools_sf,\n  sports = sports,\n  supermarkets = supermarkets\n)\n\n# Calculate ALL proximity and count features\nhdb_all_features <- calculate_custom_spatial_features(\n  hdb_sf = HDBresale_sf,\n  amenities_list = amenities,\n  proximity_amenities = names(amenities),  # All for proximity\n  count_amenities = names(amenities),      # All for counts\n  count_radii = c(350, 1000)               # Use 2 radii\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(hdb_all_features, file = \"data/rds/hdb_all_features.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_all_features <- readRDS(\"data/rds/hdb_all_features.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(hdb_all_features)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 7,715\nColumns: 53\n$ month                    <chr> \"2025-01\", \"2025-01\", \"2025-01\", \"2025-02\", \"…\n$ town                     <chr> \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO KIO\", \"AN…\n$ flat_type                <chr> \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 RO…\n$ block                    <chr> \"337\", \"310C\", \"337\", \"226\", \"310C\", \"226\", \"…\n$ street_name              <chr> \"ANG MO KIO AVE 1\", \"ANG MO KIO AVE 1\", \"ANG …\n$ storey_range             <chr> \"13 TO 15\", \"10 TO 12\", \"10 TO 12\", \"07 TO 09…\n$ floor_area_sqm           <dbl> 91, 94, 91, 91, 96, 92, 98, 97, 94, 87, 97, 8…\n$ flat_model               <chr> \"New Generation\", \"Model A\", \"New Generation\"…\n$ lease_commence_date      <dbl> 1982, 2012, 1982, 1978, 2012, 1978, 1977, 197…\n$ remaining_lease          <chr> \"56 years 03 months\", \"86 years 09 months\", \"…\n$ resale_price             <dbl> 582000, 865000, 530000, 560000, 1038000, 5420…\n$ geometry                 <POINT [m]> POINT (30036.65 38361.04), POINT (29283…\n$ PROX_BUSSTOP_2           <dbl> 117.72195, 27.27622, 118.23483, 209.19940, 28…\n$ PROX_CHILDCARE           <dbl> 153.119700, 115.577061, 152.763611, 151.02935…\n$ PROX_CLINICS             <dbl> 107.09203, 289.09879, 106.74647, 101.49620, 2…\n$ PROX_CLUBS               <dbl> 213.6654, 481.7236, 214.6075, 270.8087, 481.7…\n$ PROX_ELDERCARE           <dbl> 259.32146, 255.53899, 259.70554, 397.75595, 2…\n$ PROX_GYMS                <dbl> 464.8300, 371.6981, 463.9565, 1125.5456, 372.…\n$ PROX_HAWKERS             <dbl> 389.0387, 381.0515, 388.0711, 131.7295, 381.7…\n$ PROX_MRT_2               <dbl> 735.2593, 731.8223, 734.6813, 651.0275, 731.5…\n$ PROX_PARKS               <dbl> 426.0029, 635.0912, 425.5281, 355.5102, 636.1…\n$ PROX_PRESCHOOL           <dbl> 153.119700, 115.577061, 152.763611, 151.02935…\n$ PROX_SCHOOLS_2           <dbl> 274.3232, 426.0573, 273.8096, 223.8339, 424.9…\n$ PROX_SPORTS              <dbl> 217.5925, 527.0239, 216.6514, 270.8087, 526.0…\n$ PROX_SUPERMARKETS        <dbl> 284.4797, 314.1814, 284.7362, 185.6432, 314.7…\n$ COUNT_350M_BUSSTOP_2     <int> 7, 4, 7, 7, 4, 7, 6, 7, 5, 5, 5, 6, 6, 4, 4, …\n$ COUNT_1000M_BUSSTOP_2    <int> 45, 51, 45, 48, 51, 48, 50, 50, 51, 51, 50, 4…\n$ COUNT_350M_CHILDCARE     <int> 3, 5, 3, 5, 5, 5, 5, 7, 2, 2, 2, 2, 4, 6, 5, …\n$ COUNT_1000M_CHILDCARE    <int> 25, 27, 25, 24, 27, 24, 26, 26, 27, 27, 27, 2…\n$ COUNT_350M_CLINICS       <int> 6, 3, 6, 2, 3, 2, 2, 2, 1, 1, 3, 2, 2, 1, 3, …\n$ COUNT_1000M_CLINICS      <int> 28, 30, 28, 20, 30, 20, 30, 30, 31, 31, 31, 2…\n$ COUNT_350M_CLUBS         <int> 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, …\n$ COUNT_1000M_CLUBS        <int> 3, 5, 3, 3, 5, 3, 4, 4, 4, 4, 5, 4, 3, 4, 4, …\n$ COUNT_350M_ELDERCARE     <int> 1, 2, 1, 0, 2, 0, 2, 2, 1, 1, 1, 1, 0, 2, 1, …\n$ COUNT_1000M_ELDERCARE    <int> 4, 5, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 5, 5, 4, …\n$ COUNT_350M_GYMS          <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ COUNT_1000M_GYMS         <int> 4, 2, 4, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, …\n$ COUNT_350M_HAWKERS       <int> 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, …\n$ COUNT_1000M_HAWKERS      <int> 3, 4, 3, 3, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, …\n$ COUNT_350M_MRT_2         <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ COUNT_1000M_MRT_2        <int> 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, …\n$ COUNT_350M_PARKS         <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …\n$ COUNT_1000M_PARKS        <int> 3, 3, 3, 7, 3, 7, 5, 5, 3, 3, 5, 4, 7, 4, 4, …\n$ COUNT_350M_PRESCHOOL     <int> 3, 6, 3, 7, 6, 7, 6, 8, 2, 2, 2, 2, 6, 7, 6, …\n$ COUNT_1000M_PRESCHOOL    <int> 31, 33, 31, 29, 33, 29, 31, 30, 33, 33, 33, 3…\n$ COUNT_350M_SCHOOLS_2     <int> 2, 0, 2, 2, 0, 2, 1, 0, 0, 0, 1, 2, 2, 0, 1, …\n$ COUNT_1000M_SCHOOLS_2    <int> 4, 5, 4, 7, 5, 7, 6, 6, 5, 5, 5, 4, 7, 5, 5, …\n$ COUNT_350M_SPORTS        <int> 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, …\n$ COUNT_1000M_SPORTS       <int> 3, 2, 3, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, …\n$ COUNT_350M_SUPERMARKETS  <int> 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, …\n$ COUNT_1000M_SUPERMARKETS <int> 4, 9, 4, 5, 9, 5, 8, 7, 10, 10, 8, 8, 5, 9, 1…\n$ storey_order             <dbl> 5, 4, 4, 3, 10, 2, 4, 2, 6, 6, 2, 3, 4, 2, 1,…\n$ remaining_lease_months   <dbl> 675, 1041, 674, 624, 1040, 624, 613, 614, 103…\n```\n\n\n:::\n:::\n\n\n### 4.2 Calculating Spatial features\n\nWe convert spatial features *storey_range* and *remaining_lease* into numerical columns so that it can be used for predictive modelling.\n\nWe then remove features that are non-numeric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate ordered column for storey_range\n\nhdb_all_features <- hdb_all_features %>%\n  mutate(\n    storey_order = case_when(\n      storey_range == \"01 TO 03\" ~ 1,\n      storey_range == \"04 TO 06\" ~ 2,\n      storey_range == \"07 TO 09\" ~ 3,\n      storey_range == \"10 TO 12\" ~ 4,\n      storey_range == \"13 TO 15\" ~ 5,\n      storey_range == \"16 TO 18\" ~ 6,\n      storey_range == \"19 TO 21\" ~ 7,\n      storey_range == \"22 TO 24\" ~ 8,\n      storey_range == \"25 TO 27\" ~ 9,\n      storey_range == \"28 TO 30\" ~ 10,\n      storey_range == \"31 TO 33\" ~ 11,\n      storey_range == \"34 TO 36\" ~ 12,\n      storey_range == \"37 TO 39\" ~ 13,\n      storey_range == \"40 TO 42\" ~ 14,\n      storey_range == \"43 TO 45\" ~ 15,\n      storey_range == \"49 TO 51\" ~ 16, \n      TRUE ~ NA_real_\n    )\n  )\n\n# Convert lease_remaining to months\n\nconvert_lease_to_months <- function(lease_string) {\n  years <- as.numeric(str_extract(lease_string, \"\\\\d+(?= years?)\"))\n  months <- as.numeric(str_extract(lease_string, \"\\\\d+(?= months?)\"))\n  \n  # Handle NAs\n  years <- ifelse(is.na(years), 0, years)\n  months <- ifelse(is.na(months), 0, months)\n  \n  return((years * 12) + months)\n}\n\nhdb_all_features <- hdb_all_features %>%\n  mutate(remaining_lease_months = convert_lease_to_months(remaining_lease))\n\nhdb_numeric <- hdb_all_features %>%\n  select(-month, -town, -flat_type, -block, -street_name, -storey_range, -flat_model, -lease_commence_date, -remaining_lease)\n```\n:::\n\n\n## 5 Exploratory Data Analysis (EDA)\n\nWe plot the features and dependent variable, *Resale_Price*, using histograms. This is to understand the underlying distribution of each features.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create histograms\nhdb_eda <- hdb_numeric \n\n# Set up plotting parameters\npar(mfrow = c(4, 4))  # Adjust grid size based on number of features\npar(mar = c(3, 3, 2, 1))  # Adjust margins\n\n# Create histograms for all numeric columns\nfor(col in names(hdb_eda)) {\n  if(is.numeric(hdb_eda[[col]])) {\n    hist(hdb_numeric[[col]], \n         main = col,\n         xlab = \"\",\n         ylab = \"\",\n         col = \"lightblue\",\n         border = \"black\",\n         breaks = 30)\n  }\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-54-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Reset plotting parameters\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-54-3.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mar = c(5, 4, 4, 2) + 0.1)  # Reset to default margins\n```\n:::\n\n\nFrom the plots we can observe that:\n\n-   Most COUNT variables have right skew, hence log transformation is required.\n\n-   Some COUNT variables like `COUNT_350M_SPORTS`, `COUNT_350M_GYMS`, `COUNT_350M_CLUBS` have most values at 0 and 1. We can convert to binary attributes instead.\n\n-   Most PROX variables can be inverse transformed using *1 / (1 + df\\[\\[feature\\]\\])*, which will place more weight on closer amenities than amenities that are located further away, with a decay effect.\n\n-   `remaining_lease_months` has a left skew, as most HDB flats in Singapore have substantial lease remaining, with fewer approaching the end of their 99-year lease. We can reflect the data, and add log transformation.\n\n-   The dependent variable, `resale_price` has a right skew, hence log transformation is required.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(hdb_numeric)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"floor_area_sqm\"           \"resale_price\"            \n [3] \"geometry\"                 \"PROX_BUSSTOP_2\"          \n [5] \"PROX_CHILDCARE\"           \"PROX_CLINICS\"            \n [7] \"PROX_CLUBS\"               \"PROX_ELDERCARE\"          \n [9] \"PROX_GYMS\"                \"PROX_HAWKERS\"            \n[11] \"PROX_MRT_2\"               \"PROX_PARKS\"              \n[13] \"PROX_PRESCHOOL\"           \"PROX_SCHOOLS_2\"          \n[15] \"PROX_SPORTS\"              \"PROX_SUPERMARKETS\"       \n[17] \"COUNT_350M_BUSSTOP_2\"     \"COUNT_1000M_BUSSTOP_2\"   \n[19] \"COUNT_350M_CHILDCARE\"     \"COUNT_1000M_CHILDCARE\"   \n[21] \"COUNT_350M_CLINICS\"       \"COUNT_1000M_CLINICS\"     \n[23] \"COUNT_350M_CLUBS\"         \"COUNT_1000M_CLUBS\"       \n[25] \"COUNT_350M_ELDERCARE\"     \"COUNT_1000M_ELDERCARE\"   \n[27] \"COUNT_350M_GYMS\"          \"COUNT_1000M_GYMS\"        \n[29] \"COUNT_350M_HAWKERS\"       \"COUNT_1000M_HAWKERS\"     \n[31] \"COUNT_350M_MRT_2\"         \"COUNT_1000M_MRT_2\"       \n[33] \"COUNT_350M_PARKS\"         \"COUNT_1000M_PARKS\"       \n[35] \"COUNT_350M_PRESCHOOL\"     \"COUNT_1000M_PRESCHOOL\"   \n[37] \"COUNT_350M_SCHOOLS_2\"     \"COUNT_1000M_SCHOOLS_2\"   \n[39] \"COUNT_350M_SPORTS\"        \"COUNT_1000M_SPORTS\"      \n[41] \"COUNT_350M_SUPERMARKETS\"  \"COUNT_1000M_SUPERMARKETS\"\n[43] \"storey_order\"             \"remaining_lease_months\"  \n```\n\n\n:::\n:::\n\n\nWe then define a feature engineering function to apply the right transformations and standardisations to each variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_engineering <- function(data) {\n  df_engineered <- data\n  \n  # Define variable groups - FIXED: removed duplicates and inconsistencies\n  count_vars_right_skew <- c(\n    \"COUNT_1000M_BUSSTOP_2\", \"COUNT_1000M_CHILDCARE\", \"COUNT_350M_CHILDCARE\",\n    \"COUNT_1000M_CLINICS\", \"COUNT_1000M_CLUBS\", \"COUNT_1000M_ELDERCARE\",\n    \"COUNT_1000M_GYMS\", \"COUNT_1000M_HAWKERS\", \"COUNT_1000M_MRT_2\", \n    \"COUNT_1000M_PARKS\", \"COUNT_1000M_PRESCHOOL\", \"COUNT_1000M_SCHOOLS_2\",\n    \"COUNT_1000M_SPORTS\", \"COUNT_1000M_SUPERMARKETS\"\n  )\n  \n  count_vars_binary <- c(\n    \"COUNT_350M_BUSSTOP_2\", \"COUNT_350M_CLINICS\", \"COUNT_350M_CLUBS\", \n    \"COUNT_350M_ELDERCARE\", \"COUNT_350M_GYMS\", \"COUNT_350M_HAWKERS\",\n    \"COUNT_350M_MRT_2\", \"COUNT_350M_PARKS\", \"COUNT_350M_PRESCHOOL\",\n    \"COUNT_350M_SCHOOLS_2\", \"COUNT_350M_SPORTS\", \"COUNT_350M_SUPERMARKETS\"\n  )\n  \n  prox_vars <- c(\n    \"PROX_BUSSTOP_2\", \"PROX_CHILDCARE\", \"PROX_CLINICS\", \"PROX_CLUBS\", \n    \"PROX_ELDERCARE\", \"PROX_GYMS\", \"PROX_HAWKERS\", \"PROX_MRT_2\", \n    \"PROX_PARKS\", \"PROX_PRESCHOOL\", \"PROX_SCHOOLS_2\", \"PROX_SPORTS\", \n    \"PROX_SUPERMARKETS\"\n  )\n  \n  continuous_vars <- c(\"floor_area_sqm\", \"storey_order\")\n  \n  # 1. COUNT: Right-skewed → Log transform → Standardise\n  for(feature in count_vars_right_skew) {\n    if(feature %in% names(data)) {\n      log_transformed <- log1p(data[[feature]])\n      df_engineered[[paste0(\"STD_LOG_\", feature)]] <- as.numeric(scale(log_transformed))\n      df_engineered[[feature]] <- NULL\n    }\n  }\n  \n  # 2. COUNT: Binary distribution → Keep as 0/1 (NO standardisation)\n  for(feature in count_vars_binary) {\n    if(feature %in% names(data)) {\n      df_engineered[[paste0(\"BIN_\", feature)]] <- as.numeric(data[[feature]] > 0)\n      df_engineered[[feature]] <- NULL\n    }\n  }\n  \n  # 3. PROX: Inverse transform → Standardise\n  for(feature in prox_vars) {\n    if(feature %in% names(data)) {\n      inv_transformed <- 1 / (1 + data[[feature]])\n      df_engineered[[paste0(\"STD_INV_\", feature)]] <- as.numeric(scale(inv_transformed))\n      df_engineered[[feature]] <- NULL\n    }\n  }\n  \n  # 4. Continuous variables → Standardise\n  for(feature in continuous_vars) {\n    if(feature %in% names(data)) {\n      df_engineered[[paste0(\"STD_\", feature)]] <- as.numeric(scale(df_engineered[[feature]]))\n      df_engineered[[feature]] <- NULL\n    }\n  }\n  \n  # 5. Remaining lease: Special handling\n  if(\"remaining_lease_months\" %in% names(data)) {\n    max_lease <- max(data$remaining_lease_months, na.rm = TRUE)\n    reflected_log <- log1p(max_lease - data$remaining_lease_months)\n    df_engineered$STD_LOG_REFLECT_LEASE <- as.numeric(scale(reflected_log))\n    df_engineered$resale_price <- NULL\n  }\n  \n  # 6. Log transform the target variable AND keep original\n  if(\"resale_price\" %in% names(data)) {\n    df_engineered$log_resale_price <- log(data$resale_price)\n    # Drop the original resale_price\n    df_engineered$remaining_lease_months <- NULL\n  }\n  \n  return(df_engineered) \n}  \n\n# Apply feature engineering\nhdb_engineered <- feature_engineering(hdb_numeric)\n\n# Check the results\nglimpse(hdb_engineered)\ncat(\"Number of features after engineering:\", ncol(hdb_engineered), \"\\n\")\ncat(\"Target variables:\", names(hdb_engineered)[grepl(\"resale_price\", names(hdb_engineered))], \"\\n\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(hdb_engineered, file = \"data/rds/HDBresale_eng.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_engineered <- read_rds(\"data/rds/HDBresale_eng.rds\")\n```\n:::\n\n\n## 6 Computing Correlation Matrix\n\nWe examine if multicollinearity is present in the features.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_engineered_nogeo <- hdb_engineered %>%\n  st_drop_geometry() %>%\n  select(-log_resale_price)\n\ncorrplot::corrplot(cor(hdb_engineered_nogeo, use = \"complete.obs\"), \n                   diag = FALSE, \n                   order = \"AOE\",\n                   tl.pos = \"td\", \n                   tl.cex = 0.5, \n                   method = \"number\", \n                   type = \"upper\",\n                   title = \"Feature Correlations (Without Price)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_high_correlations <- function(cor_matrix, threshold = 0.8) {\n  cor_matrix[lower.tri(cor_matrix, diag = TRUE)] <- NA\n  cor_df <- as.data.frame(as.table(cor_matrix))\n  colnames(cor_df) <- c(\"Feature1\", \"Feature2\", \"Correlation\")\n  high_corr <- cor_df %>%\n    filter(abs(Correlation) > threshold & !is.na(Correlation)) %>%\n    arrange(desc(abs(Correlation)))\n  return(high_corr)\n}\n\ncor_matrix <- cor(hdb_engineered_nogeo, use = \"complete.obs\")\nhigh_corr_pairs <- get_high_correlations(cor_matrix, threshold = 0.8)\n\nprint(\"Highly correlated feature pairs (r > 0.8):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Highly correlated feature pairs (r > 0.8):\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhigh_corr_pairs %>% \n  as_tibble() %>% \n  print(n = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Feature1                      Feature2                      Correlation\n  <fct>                         <fct>                               <dbl>\n1 STD_INV_PROX_CHILDCARE        STD_INV_PROX_PRESCHOOL              0.995\n2 STD_LOG_COUNT_1000M_CHILDCARE STD_LOG_COUNT_1000M_PRESCHOOL       0.988\n```\n\n\n:::\n:::\n\n\nChildcare and Preschool columns are extremely correlated with each other, hence Childcare columns will be dropped.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_final <- hdb_engineered %>%\n  select(-STD_INV_PROX_CHILDCARE, -STD_LOG_COUNT_1000M_CHILDCARE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(hdb_final, \"data/model/hdb_final.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_final <- read_rds(\"data/model/hdb_final.rds\")\n```\n:::\n\n\n## 7 Building a Non-spatial Multiple Linear Regression (MLR)\n\nThis will be our base model to identify important features, and to check residuals for spatial autocorrelation.\n\n### 7.1 Data Train-test Split\n\nThe data is split into training and test data sets, 70% and 30% respectively, by using `initial_split()` of **rsample** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nhdb_sampled <- hdb_final %>%\n  sample_n(5000)\n\nresale_split <- initial_split(hdb_sampled, prop = 0.7)  # 70% train, 30% test\n\ntrain_data <- training(resale_split)\ntest_data <- testing(resale_split)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(train_data, \"data/model/train_data.rds\")\nwrite_rds(test_data, \"data/model/test_data.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data <- read_rds(\"data/model/train_data.rds\")\ntest_data <- read_rds(\"data/model/test_data.rds\")\n```\n:::\n\n\n### 7.2 Create Multiple Linear Regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_mlr <- lm(log_resale_price ~ ., \n                data = train_data %>% st_drop_geometry())\nsummary(price_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_resale_price ~ ., data = train_data %>% st_drop_geometry())\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.65495 -0.07691 -0.00992  0.07270  0.48297 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      13.3832796  0.0698738 191.535  < 2e-16 ***\nSTD_LOG_COUNT_1000M_BUSSTOP_2     0.0065374  0.0030296   2.158 0.031007 *  \nSTD_LOG_COUNT_350M_CHILDCARE     -0.0020468  0.0025606  -0.799 0.424160    \nSTD_LOG_COUNT_1000M_CLINICS       0.0157062  0.0039275   3.999 6.49e-05 ***\nSTD_LOG_COUNT_1000M_CLUBS        -0.0090770  0.0027778  -3.268 0.001095 ** \nSTD_LOG_COUNT_1000M_ELDERCARE     0.0266356  0.0028881   9.222  < 2e-16 ***\nSTD_LOG_COUNT_1000M_GYMS          0.0378115  0.0033507  11.285  < 2e-16 ***\nSTD_LOG_COUNT_1000M_HAWKERS       0.0480189  0.0032364  14.837  < 2e-16 ***\nSTD_LOG_COUNT_1000M_MRT_2         0.0120172  0.0027609   4.353 1.38e-05 ***\nSTD_LOG_COUNT_1000M_PARKS         0.0417840  0.0028522  14.650  < 2e-16 ***\nSTD_LOG_COUNT_1000M_PRESCHOOL     0.0008445  0.0042743   0.198 0.843390    \nSTD_LOG_COUNT_1000M_SCHOOLS_2    -0.0069503  0.0033349  -2.084 0.037224 *  \nSTD_LOG_COUNT_1000M_SPORTS       -0.0092702  0.0031491  -2.944 0.003264 ** \nSTD_LOG_COUNT_1000M_SUPERMARKETS  0.0103233  0.0030463   3.389 0.000710 ***\nBIN_COUNT_350M_BUSSTOP_2         -0.0490646  0.0559241  -0.877 0.380362    \nBIN_COUNT_350M_CLINICS            0.0137186  0.0082260   1.668 0.095464 .  \nBIN_COUNT_350M_CLUBS              0.0069177  0.0055164   1.254 0.209914    \nBIN_COUNT_350M_ELDERCARE          0.0217766  0.0057988   3.755 0.000176 ***\nBIN_COUNT_350M_GYMS              -0.0672989  0.0147420  -4.565 5.17e-06 ***\nBIN_COUNT_350M_HAWKERS            0.0192687  0.0081009   2.379 0.017433 *  \nBIN_COUNT_350M_MRT_2              0.0493819  0.0065817   7.503 7.89e-14 ***\nBIN_COUNT_350M_PARKS              0.0168750  0.0097030   1.739 0.082098 .  \nBIN_COUNT_350M_PRESCHOOL          0.0086832  0.0406367   0.214 0.830811    \nBIN_COUNT_350M_SCHOOLS_2          0.0045008  0.0058292   0.772 0.440102    \nBIN_COUNT_350M_SPORTS             0.0208940  0.0125370   1.667 0.095687 .  \nBIN_COUNT_350M_SUPERMARKETS       0.0124031  0.0050753   2.444 0.014582 *  \nSTD_INV_PROX_BUSSTOP_2           -0.0017886  0.0021755  -0.822 0.411045    \nSTD_INV_PROX_CLINICS              0.0007288  0.0021828   0.334 0.738502    \nSTD_INV_PROX_CLUBS                0.0095949  0.0034510   2.780 0.005460 ** \nSTD_INV_PROX_ELDERCARE           -0.0051418  0.0022929  -2.242 0.024994 *  \nSTD_INV_PROX_GYMS                 0.0115225  0.0044519   2.588 0.009688 ** \nSTD_INV_PROX_HAWKERS             -0.0138347  0.0036716  -3.768 0.000167 ***\nSTD_INV_PROX_MRT_2                0.0036486  0.0027147   1.344 0.179033    \nSTD_INV_PROX_PARKS               -0.0011940  0.0037804  -0.316 0.752146    \nSTD_INV_PROX_PRESCHOOL           -0.0013997  0.0020776  -0.674 0.500547    \nSTD_INV_PROX_SCHOOLS_2           -0.0028888  0.0026886  -1.074 0.282693    \nSTD_INV_PROX_SPORTS              -0.0121749  0.0047299  -2.574 0.010093 *  \nSTD_INV_PROX_SUPERMARKETS         0.0040052  0.0019775   2.025 0.042911 *  \nSTD_floor_area_sqm                0.0443809  0.0022285  19.915  < 2e-16 ***\nSTD_storey_order                  0.0611577  0.0022671  26.976  < 2e-16 ***\nSTD_LOG_REFLECT_LEASE            -0.1176456  0.0025358 -46.394  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1233 on 3459 degrees of freedom\nMultiple R-squared:  0.6655,\tAdjusted R-squared:  0.6616 \nF-statistic:   172 on 40 and 3459 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe adjusted R_squared = 0.661, which means that the features explain 66.1% of variability in HDB resale price. The residual SE = 0.123 which means approximately 68% of predictions will be within 88.4% to 113.1% of actual price.\n\nThe p-value is \\< 0.05, indicating that the model is statistically significant, meaning the predictors collectively contribute significantly to predicting the resale price.\n\n### 7.3 Retain Important Features\n\nFirst, we identify the features that are statistically significant (i.e. p \\< 0.05).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimportant_vars <- names(which(summary(price_mlr)$coefficients[-1, 4] < 0.05))\ncat(\"Statistically significant predictors:\", length(important_vars), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistically significant predictors: 25 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_table <- as.data.frame(summary(price_mlr)$coefficients) %>%\n  rownames_to_column(var = \"Predictor\")\n\nlabeled_features <- coef_table %>%\n  rename(P_Value = `Pr(>|t|)`) %>%\n  filter(Predictor != \"(Intercept)\") %>%\n  mutate(\n    Significance = ifelse(P_Value < 0.05, \"Significant\", \"Non-Significant\")\n  ) %>%\n  select(Predictor, Estimate, P_Value, Significance)\nprint(labeled_features)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Predictor      Estimate       P_Value    Significance\n1     STD_LOG_COUNT_1000M_BUSSTOP_2  0.0065374059  3.100654e-02     Significant\n2      STD_LOG_COUNT_350M_CHILDCARE -0.0020467740  4.241598e-01 Non-Significant\n3       STD_LOG_COUNT_1000M_CLINICS  0.0157062104  6.493849e-05     Significant\n4         STD_LOG_COUNT_1000M_CLUBS -0.0090770329  1.094688e-03     Significant\n5     STD_LOG_COUNT_1000M_ELDERCARE  0.0266355648  4.919154e-20     Significant\n6          STD_LOG_COUNT_1000M_GYMS  0.0378115288  4.992207e-29     Significant\n7       STD_LOG_COUNT_1000M_HAWKERS  0.0480189130  2.511544e-48     Significant\n8         STD_LOG_COUNT_1000M_MRT_2  0.0120172325  1.384378e-05     Significant\n9         STD_LOG_COUNT_1000M_PARKS  0.0417840178  3.415933e-47     Significant\n10    STD_LOG_COUNT_1000M_PRESCHOOL  0.0008444915  8.433901e-01 Non-Significant\n11    STD_LOG_COUNT_1000M_SCHOOLS_2 -0.0069502703  3.722427e-02     Significant\n12       STD_LOG_COUNT_1000M_SPORTS -0.0092701951  3.263811e-03     Significant\n13 STD_LOG_COUNT_1000M_SUPERMARKETS  0.0103233269  7.098828e-04     Significant\n14         BIN_COUNT_350M_BUSSTOP_2 -0.0490645838  3.803620e-01 Non-Significant\n15           BIN_COUNT_350M_CLINICS  0.0137186258  9.546449e-02 Non-Significant\n16             BIN_COUNT_350M_CLUBS  0.0069177239  2.099142e-01 Non-Significant\n17         BIN_COUNT_350M_ELDERCARE  0.0217765557  1.759279e-04     Significant\n18              BIN_COUNT_350M_GYMS -0.0672988749  5.166401e-06     Significant\n19           BIN_COUNT_350M_HAWKERS  0.0192686959  1.743333e-02     Significant\n20             BIN_COUNT_350M_MRT_2  0.0493818824  7.889795e-14     Significant\n21             BIN_COUNT_350M_PARKS  0.0168750433  8.209755e-02 Non-Significant\n22         BIN_COUNT_350M_PRESCHOOL  0.0086831807  8.308105e-01 Non-Significant\n23         BIN_COUNT_350M_SCHOOLS_2  0.0045008129  4.401024e-01 Non-Significant\n24            BIN_COUNT_350M_SPORTS  0.0208940322  9.568721e-02 Non-Significant\n25      BIN_COUNT_350M_SUPERMARKETS  0.0124030704  1.458213e-02     Significant\n26           STD_INV_PROX_BUSSTOP_2 -0.0017885647  4.110452e-01 Non-Significant\n27             STD_INV_PROX_CLINICS  0.0007287509  7.385019e-01 Non-Significant\n28               STD_INV_PROX_CLUBS  0.0095949465  5.460006e-03     Significant\n29           STD_INV_PROX_ELDERCARE -0.0051417533  2.499362e-02     Significant\n30                STD_INV_PROX_GYMS  0.0115224836  9.688218e-03     Significant\n31             STD_INV_PROX_HAWKERS -0.0138347303  1.672800e-04     Significant\n32               STD_INV_PROX_MRT_2  0.0036486459  1.790327e-01 Non-Significant\n33               STD_INV_PROX_PARKS -0.0011940025  7.521457e-01 Non-Significant\n34           STD_INV_PROX_PRESCHOOL -0.0013996513  5.005472e-01 Non-Significant\n35           STD_INV_PROX_SCHOOLS_2 -0.0028887730  2.826928e-01 Non-Significant\n36              STD_INV_PROX_SPORTS -0.0121748976  1.009350e-02     Significant\n37        STD_INV_PROX_SUPERMARKETS  0.0040051774  4.291061e-02     Significant\n38               STD_floor_area_sqm  0.0443808574  1.237880e-83     Significant\n39                 STD_storey_order  0.0611576774 1.262770e-145     Significant\n40            STD_LOG_REFLECT_LEASE -0.1176455815  0.000000e+00     Significant\n```\n\n\n:::\n:::\n\n\nNext, we filter the train and test data to remove columns that are insignificant features.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract significant predictors (p < 0.05)\nsignificant_features <- labeled_features %>%\n  filter(Significance == \"Significant\") %>%\n  pull(Predictor)\n\nprint(\"Significant features to keep:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Significant features to keep:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(significant_features)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"STD_LOG_COUNT_1000M_BUSSTOP_2\"    \"STD_LOG_COUNT_1000M_CLINICS\"     \n [3] \"STD_LOG_COUNT_1000M_CLUBS\"        \"STD_LOG_COUNT_1000M_ELDERCARE\"   \n [5] \"STD_LOG_COUNT_1000M_GYMS\"         \"STD_LOG_COUNT_1000M_HAWKERS\"     \n [7] \"STD_LOG_COUNT_1000M_MRT_2\"        \"STD_LOG_COUNT_1000M_PARKS\"       \n [9] \"STD_LOG_COUNT_1000M_SCHOOLS_2\"    \"STD_LOG_COUNT_1000M_SPORTS\"      \n[11] \"STD_LOG_COUNT_1000M_SUPERMARKETS\" \"BIN_COUNT_350M_ELDERCARE\"        \n[13] \"BIN_COUNT_350M_GYMS\"              \"BIN_COUNT_350M_HAWKERS\"          \n[15] \"BIN_COUNT_350M_MRT_2\"             \"BIN_COUNT_350M_SUPERMARKETS\"     \n[17] \"STD_INV_PROX_CLUBS\"               \"STD_INV_PROX_ELDERCARE\"          \n[19] \"STD_INV_PROX_GYMS\"                \"STD_INV_PROX_HAWKERS\"            \n[21] \"STD_INV_PROX_SPORTS\"              \"STD_INV_PROX_SUPERMARKETS\"       \n[23] \"STD_floor_area_sqm\"               \"STD_storey_order\"                \n[25] \"STD_LOG_REFLECT_LEASE\"           \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Keep only significant features + the target variable + geometry\ntrain_data_filtered <- train_data %>%\n  select(log_resale_price, all_of(significant_features), geometry)\n\ncat(\"Training data dimensions after filtering:\", dim(train_data_filtered), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining data dimensions after filtering: 3500 27 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Keep same features in test data\ntest_data_filtered <- test_data %>%\n  select(log_resale_price, all_of(significant_features), geometry)\n\ncat(\"Test data dimensions after filtering:\", dim(test_data_filtered), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTest data dimensions after filtering: 1500 27 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check if both datasets have same columns\ncat(\"Training columns:\", names(train_data_filtered), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining columns: log_resale_price STD_LOG_COUNT_1000M_BUSSTOP_2 STD_LOG_COUNT_1000M_CLINICS STD_LOG_COUNT_1000M_CLUBS STD_LOG_COUNT_1000M_ELDERCARE STD_LOG_COUNT_1000M_GYMS STD_LOG_COUNT_1000M_HAWKERS STD_LOG_COUNT_1000M_MRT_2 STD_LOG_COUNT_1000M_PARKS STD_LOG_COUNT_1000M_SCHOOLS_2 STD_LOG_COUNT_1000M_SPORTS STD_LOG_COUNT_1000M_SUPERMARKETS BIN_COUNT_350M_ELDERCARE BIN_COUNT_350M_GYMS BIN_COUNT_350M_HAWKERS BIN_COUNT_350M_MRT_2 BIN_COUNT_350M_SUPERMARKETS STD_INV_PROX_CLUBS STD_INV_PROX_ELDERCARE STD_INV_PROX_GYMS STD_INV_PROX_HAWKERS STD_INV_PROX_SPORTS STD_INV_PROX_SUPERMARKETS STD_floor_area_sqm STD_storey_order STD_LOG_REFLECT_LEASE geometry \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Test columns:\", names(test_data_filtered), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTest columns: log_resale_price STD_LOG_COUNT_1000M_BUSSTOP_2 STD_LOG_COUNT_1000M_CLINICS STD_LOG_COUNT_1000M_CLUBS STD_LOG_COUNT_1000M_ELDERCARE STD_LOG_COUNT_1000M_GYMS STD_LOG_COUNT_1000M_HAWKERS STD_LOG_COUNT_1000M_MRT_2 STD_LOG_COUNT_1000M_PARKS STD_LOG_COUNT_1000M_SCHOOLS_2 STD_LOG_COUNT_1000M_SPORTS STD_LOG_COUNT_1000M_SUPERMARKETS BIN_COUNT_350M_ELDERCARE BIN_COUNT_350M_GYMS BIN_COUNT_350M_HAWKERS BIN_COUNT_350M_MRT_2 BIN_COUNT_350M_SUPERMARKETS STD_INV_PROX_CLUBS STD_INV_PROX_ELDERCARE STD_INV_PROX_GYMS STD_INV_PROX_HAWKERS STD_INV_PROX_SPORTS STD_INV_PROX_SUPERMARKETS STD_floor_area_sqm STD_storey_order STD_LOG_REFLECT_LEASE geometry \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Columns match:\", identical(names(train_data_filtered), names(test_data_filtered)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nColumns match: TRUE \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_mlr_filtered <- lm(log_resale_price ~ ., \n                data = train_data_filtered %>% st_drop_geometry())\nsummary(price_mlr_filtered)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_resale_price ~ ., data = train_data_filtered %>% \n    st_drop_geometry())\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.64514 -0.07654 -0.01073  0.07201  0.48068 \n\nCoefficients:\n                                  Estimate Std. Error  t value Pr(>|t|)    \n(Intercept)                      13.361994   0.004458 2996.994  < 2e-16 ***\nSTD_LOG_COUNT_1000M_BUSSTOP_2     0.006170   0.002579    2.393 0.016768 *  \nSTD_LOG_COUNT_1000M_CLINICS       0.016012   0.003810    4.203 2.70e-05 ***\nSTD_LOG_COUNT_1000M_CLUBS        -0.008882   0.002752   -3.227 0.001261 ** \nSTD_LOG_COUNT_1000M_ELDERCARE     0.027378   0.002857    9.583  < 2e-16 ***\nSTD_LOG_COUNT_1000M_GYMS          0.037849   0.003320   11.401  < 2e-16 ***\nSTD_LOG_COUNT_1000M_HAWKERS       0.048962   0.003198   15.312  < 2e-16 ***\nSTD_LOG_COUNT_1000M_MRT_2         0.012775   0.002659    4.805 1.62e-06 ***\nSTD_LOG_COUNT_1000M_PARKS         0.044113   0.002389   18.466  < 2e-16 ***\nSTD_LOG_COUNT_1000M_SCHOOLS_2    -0.006340   0.002999   -2.114 0.034590 *  \nSTD_LOG_COUNT_1000M_SPORTS       -0.010293   0.003100   -3.321 0.000908 ***\nSTD_LOG_COUNT_1000M_SUPERMARKETS  0.010423   0.002940    3.545 0.000398 ***\nBIN_COUNT_350M_ELDERCARE          0.021093   0.005769    3.656 0.000260 ***\nBIN_COUNT_350M_GYMS              -0.057799   0.013632   -4.240 2.30e-05 ***\nBIN_COUNT_350M_HAWKERS            0.019184   0.008024    2.391 0.016857 *  \nBIN_COUNT_350M_MRT_2              0.054544   0.005635    9.679  < 2e-16 ***\nBIN_COUNT_350M_SUPERMARKETS       0.014073   0.004865    2.893 0.003841 ** \nSTD_INV_PROX_CLUBS                0.011413   0.003087    3.697 0.000221 ***\nSTD_INV_PROX_ELDERCARE           -0.005296   0.002292   -2.310 0.020931 *  \nSTD_INV_PROX_GYMS                 0.009960   0.004356    2.287 0.022283 *  \nSTD_INV_PROX_HAWKERS             -0.013515   0.003625   -3.729 0.000196 ***\nSTD_INV_PROX_SPORTS              -0.006641   0.003448   -1.926 0.054189 .  \nSTD_INV_PROX_SUPERMARKETS         0.004245   0.001931    2.198 0.028014 *  \nSTD_floor_area_sqm                0.044225   0.002220   19.919  < 2e-16 ***\nSTD_storey_order                  0.060957   0.002260   26.966  < 2e-16 ***\nSTD_LOG_REFLECT_LEASE            -0.118533   0.002467  -48.038  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1233 on 3474 degrees of freedom\nMultiple R-squared:  0.6637,\tAdjusted R-squared:  0.6612 \nF-statistic: 274.2 on 25 and 3474 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAfter removing 11 features:\n\nThe adjusted R_squared = 0.661, which is at a similar level as the previous model. The residual SE = 0.123 is similar level as the previous model.\n\nThe p-value is \\< 0.05, indicating that the model is statistically significant, meaning the predictors collectively contribute significantly to predicting the resale price.\n\nResidual SE and adjusted R_squared remains the same and the model will experience less overfitting with fewer features.\n\n### 7.4 Check MLR Residuals for Spatial Autocorrelation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the exact same data that was used in the model\nmodel_indices <- as.numeric(rownames(model.frame(price_mlr_filtered)))\ntrain_data_used_in_model <- train_data_filtered[model_indices, ]\n\n# Add residuals\ntrain_data_used_in_model$mlr_residuals <- residuals(price_mlr_filtered)\n\n# Perform Moran's I on the same data the model used\nmoran_test <- moran.mc(train_data_used_in_model$mlr_residuals, \n                       listw = nb2listw(knn2nb(knearneigh(st_centroid(train_data_used_in_model)))), \n                       nsim = 999)\n\ncat(\"Moran's I p-value:\", moran_test$p.value, \"\\n\")\ncat(\"Number of observations used:\", nrow(train_data_used_in_model), \"\\n\")\n\n# Save results\nsaveRDS(moran_test, \"data/model/moran_test_filtered.rds\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  train_data_used_in_model$mlr_residuals \nweights: nb2listw(knn2nb(knearneigh(st_centroid(train_data_used_in_model))))  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.82955, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\nMoran's I test on MLR residuals revealed significant spatial autocorrelation (p \\< 0.05), indicating that housing prices vary geographically across Singapore. This strongly justifies the use of spatial modeling approaches like GWR and GWRF to capture these location-specific relationship which we will explore in the following sections.\n\n## 8 Building a Geographically Weighted Regression Model (GWR)\n\nFrom Moran's I test, we ascertain that MLR residuals show spatial patterns. Hence, we build a GWR model to capture spatial heterogeneity as feature relationships with price may vary by location.\n\n### 8.1 Computing Adaptive Bandwidth\n\nFirstly, `bw.gwr()` of **GWmodel** package will be used to determine the optimal bandwidth to be used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictors <- names(train_data_filtered)\npredictors <- predictors[!predictors %in% c(\"log_resale_price\", \"geometry\")]\n\ngwr_formula <- as.formula(paste(\"log_resale_price ~\", paste(predictors, collapse = \" + \")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- bw.gwr(\n  formula = gwr_formula,  \n  data = train_data_filtered,  \n  approach = \"AIC\",\n  kernel = \"gaussian\",\n  adaptive = TRUE,\n  longlat = FALSE\n)\n\nwrite_rds(bw_adaptive, \"data/model/bw_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- read_rds(\"data/model/bw_adaptive.rds\")\n\nbw_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 74\n```\n\n\n:::\n:::\n\n\nThe optimal adaptive bandwidth of 74 neighbors was determined using AIC criterion, indicating localised spatial effects in Singapore's housing market where each regression uses the 74 closest transactions.\n\n### 8.2 Constructing the Adaptive Bandwidth GWR Model\n\nThe GWR model was calibrated with the optimal bandwidth, generating location-specific coefficients that capture how amenity effects vary geographically across Singapore.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- gwr.basic(\n  formula = gwr_formula,  \n  data = train_data_filtered,\n  bw = bw_adaptive, \n  kernel = 'gaussian', \n  adaptive = TRUE,\n  longlat = FALSE\n)\n\nwrite_rds(gwr_adaptive, \"data/model/gwr_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- read_rds(\"data/model/gwr_adaptive.rds\")\n\ngwr_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-19 21:03:38.48184 \n   Call:\n   gwr.basic(formula = gwr_formula, data = train_data_filtered, \n    bw = bw_adaptive, kernel = \"gaussian\", adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  log_resale_price\n   Independent variables:  STD_LOG_COUNT_1000M_BUSSTOP_2 STD_LOG_COUNT_1000M_CLINICS STD_LOG_COUNT_1000M_CLUBS STD_LOG_COUNT_1000M_ELDERCARE STD_LOG_COUNT_1000M_GYMS STD_LOG_COUNT_1000M_HAWKERS STD_LOG_COUNT_1000M_MRT_2 STD_LOG_COUNT_1000M_PARKS STD_LOG_COUNT_1000M_SCHOOLS_2 STD_LOG_COUNT_1000M_SPORTS STD_LOG_COUNT_1000M_SUPERMARKETS BIN_COUNT_350M_ELDERCARE BIN_COUNT_350M_GYMS BIN_COUNT_350M_HAWKERS BIN_COUNT_350M_MRT_2 BIN_COUNT_350M_SUPERMARKETS STD_INV_PROX_CLUBS STD_INV_PROX_ELDERCARE STD_INV_PROX_GYMS STD_INV_PROX_HAWKERS STD_INV_PROX_SPORTS STD_INV_PROX_SUPERMARKETS STD_floor_area_sqm STD_storey_order STD_LOG_REFLECT_LEASE\n   Number of data points: 3500\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n     Min       1Q   Median       3Q      Max \n-0.64514 -0.07654 -0.01073  0.07201  0.48068 \n\n   Coefficients:\n                                     Estimate Std. Error  t value Pr(>|t|)    \n   (Intercept)                      13.361994   0.004458 2996.994  < 2e-16 ***\n   STD_LOG_COUNT_1000M_BUSSTOP_2     0.006170   0.002579    2.393 0.016768 *  \n   STD_LOG_COUNT_1000M_CLINICS       0.016012   0.003810    4.203 2.70e-05 ***\n   STD_LOG_COUNT_1000M_CLUBS        -0.008882   0.002752   -3.227 0.001261 ** \n   STD_LOG_COUNT_1000M_ELDERCARE     0.027378   0.002857    9.583  < 2e-16 ***\n   STD_LOG_COUNT_1000M_GYMS          0.037849   0.003320   11.401  < 2e-16 ***\n   STD_LOG_COUNT_1000M_HAWKERS       0.048962   0.003198   15.312  < 2e-16 ***\n   STD_LOG_COUNT_1000M_MRT_2         0.012775   0.002659    4.805 1.62e-06 ***\n   STD_LOG_COUNT_1000M_PARKS         0.044113   0.002389   18.466  < 2e-16 ***\n   STD_LOG_COUNT_1000M_SCHOOLS_2    -0.006340   0.002999   -2.114 0.034590 *  \n   STD_LOG_COUNT_1000M_SPORTS       -0.010293   0.003100   -3.321 0.000908 ***\n   STD_LOG_COUNT_1000M_SUPERMARKETS  0.010423   0.002940    3.545 0.000398 ***\n   BIN_COUNT_350M_ELDERCARE          0.021093   0.005769    3.656 0.000260 ***\n   BIN_COUNT_350M_GYMS              -0.057799   0.013632   -4.240 2.30e-05 ***\n   BIN_COUNT_350M_HAWKERS            0.019184   0.008024    2.391 0.016857 *  \n   BIN_COUNT_350M_MRT_2              0.054544   0.005635    9.679  < 2e-16 ***\n   BIN_COUNT_350M_SUPERMARKETS       0.014073   0.004865    2.893 0.003841 ** \n   STD_INV_PROX_CLUBS                0.011413   0.003087    3.697 0.000221 ***\n   STD_INV_PROX_ELDERCARE           -0.005296   0.002292   -2.310 0.020931 *  \n   STD_INV_PROX_GYMS                 0.009960   0.004356    2.287 0.022283 *  \n   STD_INV_PROX_HAWKERS             -0.013515   0.003625   -3.729 0.000196 ***\n   STD_INV_PROX_SPORTS              -0.006641   0.003448   -1.926 0.054189 .  \n   STD_INV_PROX_SUPERMARKETS         0.004245   0.001931    2.198 0.028014 *  \n   STD_floor_area_sqm                0.044225   0.002220   19.919  < 2e-16 ***\n   STD_storey_order                  0.060957   0.002260   26.966  < 2e-16 ***\n   STD_LOG_REFLECT_LEASE            -0.118533   0.002467  -48.038  < 2e-16 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 0.1233 on 3474 degrees of freedom\n   Multiple R-squared: 0.6637\n   Adjusted R-squared: 0.6612 \n   F-statistic: 274.2 on 25 and 3474 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 52.84643\n   Sigma(hat): 0.122913\n   AIC:  -4689.379\n   AICc:  -4688.943\n   BIC:  -7802.711\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 74 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                           Min.     1st Qu.      Median\n   Intercept                        -7.3104e+00  1.3285e+01  1.3346e+01\n   STD_LOG_COUNT_1000M_BUSSTOP_2    -6.0082e-02 -9.6160e-03  8.5579e-04\n   STD_LOG_COUNT_1000M_CLINICS      -1.1128e-01 -1.9753e-02 -7.6047e-04\n   STD_LOG_COUNT_1000M_CLUBS        -7.6463e-02 -3.1862e-03  7.3613e-03\n   STD_LOG_COUNT_1000M_ELDERCARE    -2.6432e-01 -1.0505e-02 -3.5013e-05\n   STD_LOG_COUNT_1000M_GYMS         -2.9682e+00 -1.0619e-02  8.2205e-04\n   STD_LOG_COUNT_1000M_HAWKERS      -1.6503e-01 -1.3310e-02  4.7332e-03\n   STD_LOG_COUNT_1000M_MRT_2        -9.6629e-02 -3.7589e-03  1.1543e-02\n   STD_LOG_COUNT_1000M_PARKS        -1.3012e-01 -1.9117e-04  1.1279e-02\n   STD_LOG_COUNT_1000M_SCHOOLS_2    -6.4765e-02 -1.1224e-02  3.3463e-03\n   STD_LOG_COUNT_1000M_SPORTS       -1.5115e-01 -1.7425e-02  4.9245e-03\n   STD_LOG_COUNT_1000M_SUPERMARKETS -4.8647e-02 -1.3214e-02  1.6038e-03\n   BIN_COUNT_350M_ELDERCARE         -1.1756e-01 -2.1392e-02  3.6521e-03\n   BIN_COUNT_350M_GYMS              -9.7569e+13 -7.8405e-02 -1.7401e-02\n   BIN_COUNT_350M_HAWKERS           -6.4842e-02 -1.2498e-02  4.4599e-03\n   BIN_COUNT_350M_MRT_2             -1.8486e-01  1.1453e-02  3.3996e-02\n   BIN_COUNT_350M_SUPERMARKETS      -4.9507e-02  4.0695e-03  1.6891e-02\n   STD_INV_PROX_CLUBS               -5.7887e-01 -1.4262e-02 -2.9817e-03\n   STD_INV_PROX_ELDERCARE           -1.0251e+00 -7.9859e-03 -2.5417e-04\n   STD_INV_PROX_GYMS                -1.0382e+01 -2.1929e-02  1.1652e-02\n   STD_INV_PROX_HAWKERS             -3.5172e-01 -2.1781e-02 -3.6468e-03\n   STD_INV_PROX_SPORTS              -1.4326e+02 -1.6288e-02  2.7475e-03\n   STD_INV_PROX_SUPERMARKETS        -7.0493e-01  3.8665e-04  4.1147e-03\n   STD_floor_area_sqm               -1.9278e-01  2.9676e-02  3.7613e-02\n   STD_storey_order                  2.7032e-02  4.0989e-02  4.7574e-02\n   STD_LOG_REFLECT_LEASE            -2.4904e-01 -1.5254e-01 -1.1203e-01\n                                        3rd Qu.       Max.\n   Intercept                         1.3448e+01 1.5043e+01\n   STD_LOG_COUNT_1000M_BUSSTOP_2     1.6763e-02 5.4200e-02\n   STD_LOG_COUNT_1000M_CLINICS       2.2709e-02 9.5400e-02\n   STD_LOG_COUNT_1000M_CLUBS         2.1447e-02 7.7900e-02\n   STD_LOG_COUNT_1000M_ELDERCARE     1.9651e-02 9.4500e-02\n   STD_LOG_COUNT_1000M_GYMS          1.8479e-02 2.1180e-01\n   STD_LOG_COUNT_1000M_HAWKERS       2.3595e-02 9.5400e-02\n   STD_LOG_COUNT_1000M_MRT_2         3.8503e-02 1.3890e-01\n   STD_LOG_COUNT_1000M_PARKS         2.2749e-02 8.3200e-02\n   STD_LOG_COUNT_1000M_SCHOOLS_2     1.9341e-02 8.3200e-02\n   STD_LOG_COUNT_1000M_SPORTS        2.6791e-02 3.0110e-01\n   STD_LOG_COUNT_1000M_SUPERMARKETS  1.5315e-02 1.0360e-01\n   BIN_COUNT_350M_ELDERCARE          2.5091e-02 3.0200e-01\n   BIN_COUNT_350M_GYMS               9.2323e-03 1.2870e+14\n   BIN_COUNT_350M_HAWKERS            3.9028e-02 8.8600e-02\n   BIN_COUNT_350M_MRT_2              6.2735e-02 2.5690e-01\n   BIN_COUNT_350M_SUPERMARKETS       3.4619e-02 9.5300e-02\n   STD_INV_PROX_CLUBS                2.0057e-02 8.4100e-02\n   STD_INV_PROX_ELDERCARE            3.4821e-03 5.8480e-01\n   STD_INV_PROX_GYMS                 3.8037e-02 1.2355e+02\n   STD_INV_PROX_HAWKERS              1.4443e-02 2.1060e-01\n   STD_INV_PROX_SPORTS               2.0529e-02 1.1684e+01\n   STD_INV_PROX_SUPERMARKETS         1.3217e-02 3.0890e-01\n   STD_floor_area_sqm                4.8463e-02 1.0890e-01\n   STD_storey_order                  5.3643e-02 7.4800e-02\n   STD_LOG_REFLECT_LEASE            -9.0144e-02 2.2300e-02\n   ************************Diagnostic information*************************\n   Number of data points: 3500 \n   Effective number of parameters (2trace(S) - trace(S'S)): 644.3773 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 2855.623 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): -9412.298 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): -10112.75 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): -9906.363 \n   Residual sum of squares: 9.82957 \n   R-square value:  0.9374395 \n   Adjusted R-square value:  0.9233176 \n\n   ***********************************************************************\n   Program stops at: 2025-11-19 21:03:51.409649 \n```\n\n\n:::\n:::\n\n\n### 8.3 Computing Adaptive Bandwidth for the Test Data\n\nThe bandwidth calculation is repeated, specifically using the coordinates of the test data locations, to compare against train data bandwidth calculations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictors <- names(test_data)\npredictors <- predictors[!predictors %in% c(\"log_resale_price\", \"geometry\")]\n\ngwr_formula_test <- as.formula(paste(\"log_resale_price ~\", paste(predictors, collapse = \" + \")))\n\ngwr_bw_test_adaptive <- bw.gwr(\n  formula = gwr_formula,  \n  data = test_data_filtered,\n  approach = \"AIC\",\n  kernel = \"gaussian\",\n  adaptive = TRUE,\n  longlat = FALSE\n)\n\nwrite_rds(gwr_bw_test_adaptive, \"data/model/gwr_bw_test_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_bw_test_adaptive <- read_rds(\"data/model/gwr_bw_test_adaptive.rds\")\n\ngwr_bw_test_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32\n```\n\n\n:::\n:::\n\n\nFor test data sample, the optimal adaptive bandwidth of 32 neighbors was determined using AIC criterion. However since this differs greatly from the training adaptive bandwidth (74 neighbours), we will use the training adaptive bandwidth.\n\n### 8.4 Computing Predicted Values of the Test Data\n\nWe then generate the predictions from test data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_sp_filtered <- as_Spatial(train_data_filtered)\ntest_sp_filtered  <- as_Spatial(test_data_filtered)\n\ngwr_pred <- gwr.predict(\n  formula = gwr_formula, \n  data = train_sp_filtered,          \n  predictdata = test_sp_filtered,    \n  bw = bw_adaptive, \n  kernel = 'gaussian', \n  adaptive = TRUE, \n  longlat = FALSE)\n\nwrite_rds(gwr_pred, \n          \"data/model/gwr_pred.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_pred <- read_rds(\"data/model/gwr_pred.rds\")\n\ngwr_pred\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-19 21:05:01.519297 \n   Call:\n   gwr.predict(formula = gwr_formula, data = train_sp_filtered, \n    predictdata = test_sp_filtered, bw = bw_adaptive, kernel = \"gaussian\", \n    adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable for prediction:  log_resale_price\n   Independent variables:  STD_LOG_COUNT_1000M_BUSSTOP_2 STD_LOG_COUNT_1000M_CLINICS STD_LOG_COUNT_1000M_CLUBS STD_LOG_COUNT_1000M_ELDERCARE STD_LOG_COUNT_1000M_GYMS STD_LOG_COUNT_1000M_HAWKERS STD_LOG_COUNT_1000M_MRT_2 STD_LOG_COUNT_1000M_PARKS STD_LOG_COUNT_1000M_SCHOOLS_2 STD_LOG_COUNT_1000M_SPORTS STD_LOG_COUNT_1000M_SUPERMARKETS BIN_COUNT_350M_ELDERCARE BIN_COUNT_350M_GYMS BIN_COUNT_350M_HAWKERS BIN_COUNT_350M_MRT_2 BIN_COUNT_350M_SUPERMARKETS STD_INV_PROX_CLUBS STD_INV_PROX_ELDERCARE STD_INV_PROX_GYMS STD_INV_PROX_HAWKERS STD_INV_PROX_SPORTS STD_INV_PROX_SUPERMARKETS STD_floor_area_sqm STD_storey_order STD_LOG_REFLECT_LEASE\n   Number of data points: 3500\n   ***********************************************************************\n   *     Results of Geographically Weighted Regression for prediction    *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 74 (number of nearest neighbours)\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                                Min.     1st Qu.      Median\n   Intercept_coef                        -1.0067e+01  1.3285e+01  1.3337e+01\n   STD_LOG_COUNT_1000M_BUSSTOP_2_coef    -6.0115e-02 -9.1575e-03  1.1005e-03\n   STD_LOG_COUNT_1000M_CLINICS_coef      -1.0795e-01 -1.9737e-02 -2.9836e-04\n   STD_LOG_COUNT_1000M_CLUBS_coef        -7.0177e-02 -2.9392e-03  7.1981e-03\n   STD_LOG_COUNT_1000M_ELDERCARE_coef    -2.7804e-01 -9.6397e-03  5.9354e-04\n   STD_LOG_COUNT_1000M_GYMS_coef         -2.2161e+00 -1.0604e-02  7.8061e-04\n   STD_LOG_COUNT_1000M_HAWKERS_coef      -1.6503e-01 -1.2738e-02  4.6975e-03\n   STD_LOG_COUNT_1000M_MRT_2_coef        -9.6703e-02 -3.6531e-03  1.0068e-02\n   STD_LOG_COUNT_1000M_PARKS_coef        -1.2153e-01 -2.0640e-04  1.1070e-02\n   STD_LOG_COUNT_1000M_SCHOOLS_2_coef    -6.4734e-02 -1.0605e-02  2.4279e-03\n   STD_LOG_COUNT_1000M_SPORTS_coef       -1.4213e-01 -1.4947e-02  4.6815e-03\n   STD_LOG_COUNT_1000M_SUPERMARKETS_coef -5.0771e-02 -1.5281e-02  1.6707e-03\n   BIN_COUNT_350M_ELDERCARE_coef         -1.1717e-01 -2.3320e-02 -9.5908e-04\n   BIN_COUNT_350M_GYMS_coef              -2.2162e+15 -7.4143e-02 -1.5637e-02\n   BIN_COUNT_350M_HAWKERS_coef           -6.3114e-02 -1.3346e-02  3.0411e-03\n   BIN_COUNT_350M_MRT_2_coef             -1.9549e-01  1.2531e-02  3.3505e-02\n   BIN_COUNT_350M_SUPERMARKETS_coef      -4.8495e-02  3.9190e-03  1.6625e-02\n   STD_INV_PROX_CLUBS_coef               -5.7563e-01 -1.3877e-02 -1.2414e-03\n   STD_INV_PROX_ELDERCARE_coef           -1.0263e+00 -8.3695e-03 -4.2199e-04\n   STD_INV_PROX_GYMS_coef                -1.0328e+01 -2.1527e-02  1.2008e-02\n   STD_INV_PROX_HAWKERS_coef             -2.7248e-01 -1.6410e-02 -2.9198e-03\n   STD_INV_PROX_SPORTS_coef              -1.6244e+02 -1.7946e-02  3.2216e-03\n   STD_INV_PROX_SUPERMARKETS_coef        -6.9641e-01  5.5806e-04  4.1304e-03\n   STD_floor_area_sqm_coef               -1.9277e-01  2.9878e-02  3.7414e-02\n   STD_storey_order_coef                  2.6591e-02  4.0717e-02  4.7971e-02\n   STD_LOG_REFLECT_LEASE_coef            -2.4887e-01 -1.5121e-01 -1.1200e-01\n                                             3rd Qu.       Max.\n   Intercept_coef                         1.3445e+01 1.5034e+01\n   STD_LOG_COUNT_1000M_BUSSTOP_2_coef     1.7518e-02 5.4200e-02\n   STD_LOG_COUNT_1000M_CLINICS_coef       2.3288e-02 9.3400e-02\n   STD_LOG_COUNT_1000M_CLUBS_coef         2.0306e-02 7.6100e-02\n   STD_LOG_COUNT_1000M_ELDERCARE_coef     2.0568e-02 9.0200e-02\n   STD_LOG_COUNT_1000M_GYMS_coef          1.7821e-02 1.8630e-01\n   STD_LOG_COUNT_1000M_HAWKERS_coef       2.2196e-02 9.3200e-02\n   STD_LOG_COUNT_1000M_MRT_2_coef         3.6776e-02 1.3920e-01\n   STD_LOG_COUNT_1000M_PARKS_coef         2.3465e-02 8.1900e-02\n   STD_LOG_COUNT_1000M_SCHOOLS_2_coef     1.8967e-02 8.3200e-02\n   STD_LOG_COUNT_1000M_SPORTS_coef        2.8244e-02 3.3370e-01\n   STD_LOG_COUNT_1000M_SUPERMARKETS_coef  1.5545e-02 1.0340e-01\n   BIN_COUNT_350M_ELDERCARE_coef          2.0492e-02 3.0170e-01\n   BIN_COUNT_350M_GYMS_coef               9.1188e-03 1.7405e+13\n   BIN_COUNT_350M_HAWKERS_coef            3.3938e-02 8.7200e-02\n   BIN_COUNT_350M_MRT_2_coef              6.1636e-02 2.5590e-01\n   BIN_COUNT_350M_SUPERMARKETS_coef       3.5715e-02 9.5000e-02\n   STD_INV_PROX_CLUBS_coef                1.9486e-02 7.9500e-02\n   STD_INV_PROX_ELDERCARE_coef            3.4577e-03 4.4100e-01\n   STD_INV_PROX_GYMS_coef                 3.6865e-02 1.4014e+02\n   STD_INV_PROX_HAWKERS_coef              1.4212e-02 2.0270e-01\n   STD_INV_PROX_SPORTS_coef               1.8660e-02 1.1621e+01\n   STD_INV_PROX_SUPERMARKETS_coef         1.4537e-02 2.8250e-01\n   STD_floor_area_sqm_coef                4.8893e-02 1.0490e-01\n   STD_storey_order_coef                  5.3828e-02 7.4800e-02\n   STD_LOG_REFLECT_LEASE_coef            -9.1700e-02 2.2300e-02\n\n   ****************       Results of GW prediction       ******************\n                        Min.    1st Qu.     Median    3rd Qu.    Max.\n   prediction      9.8945603 13.2411362 13.3429793 13.4750830 16.2786\n   prediction_var  0.0035232  0.0036946  0.0037842  0.0039355  6.3607\n\n   ***********************************************************************\n   Program stops at: 2025-11-19 21:43:49.584612 \n```\n\n\n:::\n:::\n\n\n## 9 Building a Random Forest Model\n\nRandom Forest is a non-parametric ensemble method that is robust to multicollinearity and automatically handles complex, non-linear relationships. We use it here as a high-performance predictive benchmark against the GWR model.\n\nWe will calibrate a Random Forest model to predict HDB resale price by using `random forest` function of **ranger** package.\n\n### 9.1 Preparing Data for Non-Spatial RF\n\nSince Random Forest does not use geographic coordinates for its core calculations, we strip the *geometry* column from the filtered training and test datasets using `st_drop_geometry()` of **sf** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_rf <- train_data_filtered %>% \n  st_drop_geometry()\n\ntest_rf <- test_data_filtered %>% \n  st_drop_geometry()\n```\n:::\n\n\n### 9.2 Constructing the Random Forest Model\n\nWe use the **ranger** package to fit the RF model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictors <- names(train_data_filtered)\npredictors <- predictors[!predictors %in% c(\"log_resale_price\", \"geometry\")]\n\ngwr_formula <- as.formula(paste(\"log_resale_price ~\", paste(predictors, collapse = \" + \")))\n\n# The RF model will be trained on the log-transformed price\nset.seed(42) \nrf_model <- ranger::ranger(\n  formula = gwr_formula,              \n  data = train_rf,                    \n  num.trees = 500,                    \n  importance = \"permutation\",         \n  seed = 42                           \n)\n\nwrite_rds(rf_model, \"data/model/rf_model.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf_model <- read_rds(\"data/model/rf_model.rds\")\n\nrf_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRanger result\n\nCall:\n ranger::ranger(formula = gwr_formula, data = train_rf, num.trees = 500,      importance = \"permutation\", seed = 42) \n\nType:                             Regression \nNumber of trees:                  500 \nSample size:                      3500 \nNumber of independent variables:  25 \nMtry:                             5 \nTarget node size:                 5 \nVariable importance mode:         permutation \nSplitrule:                        variance \nOOB prediction error (MSE):       0.00385201 \nR squared (OOB):                  0.9142178 \n```\n\n\n:::\n:::\n\n\n### 9.3 Computing Predicted Values of the Test Data\n\nWe then generate the predictions from test data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf_pred <- predict(rf_model, data = test_rf)\n\n# The prediction object contains the predicted values in the 'predictions' slot\nrf_pred_values <- rf_pred$predictions\n\nwrite_rds(rf_pred_values, \"data/model/rf_pred.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf_pred <- read_rds(\"data/model/rf_pred.rds\")\n\nrf_pred\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   [1] 13.27545 13.35583 13.50883 13.25407 13.80275 13.66986 13.38479 13.26394\n   [9] 13.43419 13.58709 13.22958 13.44351 13.17996 13.46350 13.27303 13.16935\n  [17] 13.31519 13.35065 13.45326 13.24131 13.26232 13.57734 13.30347 13.42917\n  [25] 13.35208 13.55303 13.29064 13.21037 13.26300 13.37619 13.26652 13.30326\n  [33] 13.43341 13.58029 13.23968 13.26766 13.25536 13.20821 13.41878 13.19520\n  [41] 13.79781 13.25755 13.15870 13.18420 13.16434 13.37276 13.18106 13.22500\n  [49] 13.96511 13.44607 13.29046 13.32593 13.23474 13.39554 13.29880 13.37773\n  [57] 13.34959 13.15145 13.22358 13.24729 13.29354 13.37107 13.37584 13.59818\n  [65] 13.83312 13.26868 13.34714 13.29323 13.26841 13.37066 13.37939 13.28107\n  [73] 13.86587 13.44880 13.20065 13.25540 13.34379 13.18244 13.56667 13.40797\n  [81] 13.57037 13.17217 13.42750 13.23304 13.79224 13.18119 13.25647 13.37146\n  [89] 13.42277 13.22863 13.37870 13.20108 13.32658 13.27317 13.40602 13.22326\n  [97] 13.31460 13.21528 13.68205 13.09441 13.35048 13.57031 13.48168 13.26579\n [105] 13.41947 13.30741 14.03269 13.28493 13.63864 13.73405 13.56833 13.25697\n [113] 13.36450 13.22094 13.31322 13.25272 13.58780 13.53675 13.14324 13.29421\n [121] 13.39573 13.29280 13.14553 13.60129 13.33868 13.77045 13.10818 13.71137\n [129] 13.90786 13.53032 13.20803 13.10702 13.53471 13.17751 14.11838 13.44181\n [137] 13.43484 13.13533 13.30529 13.40915 13.29114 13.53646 13.73935 13.95846\n [145] 13.16990 13.34563 13.67696 13.24477 13.42764 13.29396 13.43993 13.49088\n [153] 13.78980 13.27611 13.41569 13.22221 13.45575 13.28623 13.26776 13.40217\n [161] 13.27939 13.78923 13.60324 13.41433 13.47767 13.27946 13.27905 13.27284\n [169] 13.21623 13.39695 13.78196 13.36452 13.54616 13.65365 13.44176 13.14963\n [177] 13.38773 13.43914 13.49288 13.45712 13.14826 13.25109 13.40909 13.34218\n [185] 13.88920 13.81458 13.44180 13.79013 13.45132 13.33513 13.86623 13.24966\n [193] 13.40209 13.85722 13.44557 13.29833 13.20374 13.32661 13.58871 13.33699\n [201] 13.27936 13.27383 13.63160 13.42966 13.68854 13.30493 13.27540 13.32626\n [209] 13.36204 13.41712 13.47019 13.38850 13.51007 13.19569 13.22808 13.50996\n [217] 13.97941 13.33571 13.55188 13.32112 13.62871 13.26681 13.14778 13.25535\n [225] 13.27406 13.77392 13.22610 13.30035 13.29410 13.19561 13.91034 13.32632\n [233] 13.40017 13.30948 13.58294 13.33488 13.40664 13.77537 13.78210 13.40286\n [241] 13.54057 13.08349 13.27361 13.15978 13.24133 13.34203 13.36923 13.15031\n [249] 13.25863 13.19671 13.43854 13.29182 13.26077 13.17772 13.42402 13.31938\n [257] 13.37365 13.34018 13.26820 13.70059 13.27274 13.34459 13.27118 13.23132\n [265] 13.14436 13.48141 13.22837 13.21199 13.29873 13.31486 13.36135 13.34722\n [273] 13.26681 13.57184 13.21929 13.19371 13.23638 13.22302 13.14717 13.24101\n [281] 13.24018 13.24814 13.52264 13.19504 13.24372 13.13233 13.30410 13.50735\n [289] 13.59382 13.47482 13.67327 13.41683 13.52246 13.25970 13.93531 13.38332\n [297] 13.23695 13.28164 13.26555 13.22800 13.18847 13.55329 13.32947 13.81275\n [305] 13.33176 13.23084 13.84942 13.68520 13.37359 13.38224 13.26760 13.33126\n [313] 13.38177 13.39171 13.49508 13.78852 13.20759 13.36778 13.23553 13.14172\n [321] 13.83032 13.37101 13.43025 13.27254 13.17279 13.38464 13.40846 13.42553\n [329] 13.16729 13.30889 13.22515 13.28485 13.28753 13.13759 13.20628 13.38271\n [337] 13.28630 13.32930 13.76910 13.50622 13.91693 13.28949 13.23941 13.23423\n [345] 13.22172 13.23682 13.43675 13.36770 13.24158 13.27612 13.21941 13.55451\n [353] 13.87827 13.59169 13.41174 13.21888 13.35508 13.20335 13.40124 13.19738\n [361] 13.16101 13.27001 13.71452 13.39252 13.77954 13.92374 13.11670 13.34854\n [369] 13.25374 13.53687 13.28045 13.23129 13.25751 13.28858 13.32615 13.68540\n [377] 13.39523 13.18190 13.19663 13.42680 13.22699 13.77151 13.35822 13.37419\n [385] 13.26188 13.39106 13.37705 13.95725 13.88816 13.24543 13.32434 13.64887\n [393] 13.24681 13.76940 13.41966 13.20196 13.49804 13.40887 13.67339 13.57165\n [401] 13.19845 13.52847 13.19585 13.61164 13.34987 13.20793 13.39229 13.30437\n [409] 13.33601 13.23524 13.30558 13.20806 13.67051 13.80916 13.49781 13.89677\n [417] 13.30173 13.56450 13.78581 13.63668 13.24247 13.35880 13.85950 13.89538\n [425] 13.36820 13.23684 13.19044 13.33324 13.29724 13.20640 13.72766 13.61294\n [433] 13.19808 13.26723 13.35453 13.38623 13.20398 13.82545 13.90086 13.35359\n [441] 13.32207 13.21013 13.44862 13.16764 13.31879 13.21497 13.59283 13.40369\n [449] 13.77846 13.28182 13.61240 13.31076 13.33984 13.33948 13.80059 13.20720\n [457] 13.26502 13.41917 13.27536 13.57777 13.21391 13.40609 13.71867 13.22409\n [465] 13.23661 13.27279 13.55021 13.25789 13.26364 13.21323 13.20835 13.73182\n [473] 13.22831 13.23835 13.22946 13.59531 13.43861 13.33226 13.41021 13.34491\n [481] 13.25474 13.27090 13.52071 13.21597 13.55170 13.43172 13.08580 13.49068\n [489] 13.19523 13.40227 13.23693 13.44401 13.32575 13.42340 13.35507 13.30530\n [497] 13.27694 13.34086 13.83759 13.46808 13.24684 13.31099 13.50272 13.28958\n [505] 13.54243 13.24029 13.32147 13.33602 13.26573 13.17561 13.39177 13.46307\n [513] 13.48062 13.26414 13.43903 13.62211 13.22573 13.20604 13.32694 13.41016\n [521] 13.41064 13.41909 13.58628 13.14084 13.85560 13.26802 13.32893 13.25733\n [529] 13.25529 13.24095 13.32904 13.23493 13.43311 13.42337 13.52713 13.46841\n [537] 13.29998 13.14434 13.11182 13.25314 13.32068 13.34460 13.38459 13.17118\n [545] 13.32733 13.35956 13.58628 13.19975 13.20729 13.30384 13.24328 13.57865\n [553] 13.31507 13.23036 13.78375 13.40065 13.92514 13.55334 13.72227 13.17087\n [561] 13.41772 13.34687 13.46951 13.40657 13.31137 13.26587 13.30541 13.56180\n [569] 13.16480 13.20927 13.43372 13.28483 13.10200 13.28326 13.40055 13.37970\n [577] 13.53463 13.26720 13.27232 13.20367 13.41958 13.25547 13.54551 13.38841\n [585] 13.20248 13.23361 13.41017 13.31005 13.38182 13.29109 13.20185 13.13330\n [593] 13.75902 13.25897 13.24417 13.24607 13.18060 13.42303 13.21500 13.44378\n [601] 13.32525 13.57165 13.53712 13.32515 13.09250 13.25827 13.20305 13.44338\n [609] 13.34418 13.27158 13.40959 13.28087 13.19789 13.59888 13.36280 13.65941\n [617] 13.44354 13.46345 13.26160 13.45242 13.27681 13.37298 13.84941 13.26933\n [625] 13.18933 13.71917 13.16687 13.44400 13.55236 13.49740 13.39556 13.26845\n [633] 13.11257 13.22055 13.32261 13.38235 13.76162 13.16198 13.18167 13.16431\n [641] 13.67736 14.03816 13.53438 13.38783 13.77966 13.32241 13.29124 13.14442\n [649] 13.28019 13.26330 13.48460 13.57485 13.42321 13.32169 13.39083 13.33637\n [657] 13.25471 13.45390 13.62697 13.28091 13.48220 13.61151 13.71035 13.24259\n [665] 13.41049 13.39753 13.30092 13.19254 13.70185 13.36246 13.24463 13.61209\n [673] 13.34228 13.78059 13.86629 13.35282 13.35186 13.46674 13.28406 13.23369\n [681] 13.27888 13.23424 13.23716 13.52181 13.34987 13.30720 13.79318 13.17473\n [689] 13.33982 13.50130 13.33450 13.22618 13.42558 13.31344 13.54436 13.42108\n [697] 13.26609 13.39100 13.16929 13.28546 13.18252 13.37411 13.37313 13.29807\n [705] 13.37847 13.27568 13.55600 13.36057 13.43624 13.26580 13.32753 13.16710\n [713] 13.15146 13.89562 13.23597 13.56266 13.75312 13.72866 13.23676 13.23467\n [721] 13.22985 13.47580 13.18181 13.53146 13.24189 13.40684 13.35738 13.39988\n [729] 13.49772 13.26531 13.35905 13.39408 13.42581 13.22520 13.48880 13.32793\n [737] 13.24653 13.36023 13.29685 13.84284 13.90364 13.41063 13.30022 13.76890\n [745] 13.88769 13.53485 13.21716 13.34909 13.50768 13.24219 13.26207 13.33447\n [753] 13.29219 13.29128 13.52517 13.39078 13.26728 13.61142 13.48858 13.17140\n [761] 13.60274 13.23447 13.50181 13.40199 13.17478 13.29106 13.26087 13.41638\n [769] 13.15814 13.41248 13.35100 13.34991 13.92521 13.28634 13.31341 13.17456\n [777] 13.36481 13.33134 13.45405 13.35848 13.21712 13.87332 13.23152 13.84271\n [785] 13.40534 13.38868 13.81527 13.13517 13.86726 13.27209 13.35448 13.63131\n [793] 13.18814 13.32168 13.54688 13.38831 13.49286 13.24241 13.33342 13.17799\n [801] 13.78814 13.25081 13.17524 13.28025 13.35316 13.28540 13.26614 13.52354\n [809] 13.28167 13.40106 13.19160 13.51519 13.22142 13.34408 13.44880 13.22780\n [817] 13.49566 13.26493 13.49789 13.37912 13.40772 13.23223 13.20534 13.38344\n [825] 13.29759 13.38794 13.26665 13.19462 13.22830 13.25751 13.42987 13.23295\n [833] 13.46783 13.23864 13.89682 13.22302 13.47392 13.43621 13.41200 13.56583\n [841] 13.43794 13.49196 13.75686 13.26204 13.33992 13.41743 13.36954 13.40593\n [849] 13.55326 13.88036 13.86528 13.14207 13.32719 13.25974 13.61381 13.33896\n [857] 13.44140 13.38816 13.27204 13.39279 13.36443 13.73674 13.22962 13.09952\n [865] 13.14550 13.31860 13.45724 13.64573 13.26345 13.68548 13.69142 13.43464\n [873] 13.22138 13.29788 13.29975 13.57965 13.58741 13.67063 13.28106 13.44534\n [881] 13.37654 13.48501 13.31464 13.39611 13.29575 13.39181 13.32641 13.26873\n [889] 13.21848 13.32570 13.28632 13.26156 13.61824 13.56779 13.91456 13.43770\n [897] 13.42261 13.41796 13.95935 13.40742 13.74726 13.30147 13.41307 13.50385\n [905] 13.45182 13.34827 13.40039 13.27003 13.31717 13.54563 13.15010 13.75603\n [913] 13.09712 13.48184 13.27499 13.31469 13.33334 13.25267 13.20923 13.73619\n [921] 13.40618 13.32645 13.25086 13.44011 13.18735 13.45277 13.31792 13.21589\n [929] 13.22241 13.20531 13.91043 13.20522 13.32444 13.42419 13.60263 13.23216\n [937] 13.31712 13.35657 13.58862 13.31389 13.37992 13.20031 13.27340 13.53800\n [945] 13.55172 13.20619 13.37042 13.37385 13.35910 13.33527 13.35443 13.23286\n [953] 13.16958 13.88635 13.65052 13.82163 13.56618 13.46323 13.18139 13.24684\n [961] 13.83308 13.32596 13.35435 13.45714 13.19624 13.28439 13.12532 13.12081\n [969] 13.45536 13.44122 13.43579 13.41273 13.56198 13.31446 13.21554 13.32367\n [977] 13.24709 13.89593 13.17621 13.41311 13.36444 13.44365 13.27025 13.29463\n [985] 13.30456 13.17980 13.47354 13.71994 13.67936 13.25768 13.93901 13.22838\n [993] 13.77371 13.18145 13.57166 13.35029 13.22441 13.42691 13.23005 13.48179\n[1001] 13.41854 13.39763 13.82742 13.55283 13.74508 13.32865 13.19711 13.54027\n[1009] 13.35772 13.43747 13.16980 13.19875 13.53016 13.40457 13.28942 13.26334\n[1017] 13.44729 13.75152 13.44957 13.85099 13.41806 13.45500 13.37584 13.39110\n[1025] 13.24480 13.33101 13.20167 13.28639 13.79963 13.31003 13.26884 13.35274\n[1033] 13.83557 13.65571 13.62181 13.25511 13.16014 13.31536 13.39199 13.47142\n[1041] 13.25772 13.15475 13.31508 13.20775 13.25279 13.17973 13.22675 13.29144\n[1049] 14.12845 13.83467 13.29429 13.83612 13.44629 13.33829 13.43044 13.40476\n[1057] 13.20569 13.26396 13.29809 13.29621 13.23666 13.25113 13.57209 13.25377\n[1065] 13.34482 13.26227 13.29549 13.24983 13.27174 13.41095 13.23784 13.68400\n[1073] 13.32787 13.40595 13.28338 13.31616 13.24910 13.45183 13.45804 13.49632\n[1081] 13.28283 13.40642 13.23709 13.34202 13.32756 13.34670 13.35987 13.35225\n[1089] 13.38289 13.93926 13.24817 13.24886 13.10122 13.21794 13.22669 13.26839\n[1097] 13.24451 13.24032 13.29959 13.22051 13.27212 13.41229 13.45129 13.09011\n[1105] 13.29389 13.20852 13.54915 13.57230 13.28349 13.47916 13.23731 13.42878\n[1113] 13.27422 13.38758 13.18187 13.21918 13.23742 13.22653 13.26850 13.60685\n[1121] 13.41064 13.46999 13.48763 13.40959 13.23933 13.45342 13.34000 13.39570\n[1129] 13.29373 13.27984 13.35730 13.31883 13.34805 13.26349 13.08306 13.30598\n[1137] 13.33731 13.75582 13.29884 13.22195 13.20968 13.27004 13.25811 13.28514\n[1145] 13.20148 13.73001 13.28141 13.37554 13.22652 13.42596 13.33518 13.62003\n[1153] 13.30061 13.82717 13.68541 13.58812 13.39718 13.44614 13.42514 13.32516\n[1161] 13.09740 13.32746 13.38563 13.81197 13.29116 13.23595 13.67465 13.33443\n[1169] 13.46075 13.72971 13.80086 13.26519 13.64752 13.68620 13.39746 13.32964\n[1177] 13.34595 13.31679 13.19653 13.37215 13.21219 13.26994 13.11971 13.15368\n[1185] 13.15442 13.79063 13.26283 13.37324 13.32800 13.35216 13.61711 13.25277\n[1193] 13.77062 13.18173 13.19334 13.36260 13.39439 13.56846 13.72736 13.39675\n[1201] 13.35530 13.37517 13.44086 13.42081 13.22196 13.35721 13.55010 13.38463\n[1209] 13.23280 13.43214 13.50002 13.72021 13.67139 13.08483 13.71875 13.31174\n[1217] 13.21526 13.55522 13.21510 13.29408 13.17239 13.34503 13.34971 13.39258\n[1225] 13.30707 13.39355 13.47444 13.36080 13.47847 13.33410 13.23263 13.36232\n[1233] 13.16877 13.49664 13.20247 13.29115 13.20038 13.80665 13.31753 13.40487\n[1241] 13.41850 13.20195 13.20859 13.38965 13.35137 13.15214 13.40504 13.33442\n[1249] 13.38837 13.41419 13.20808 13.32053 13.27621 13.29531 13.23828 13.44253\n[1257] 13.62665 13.46345 13.23006 13.29679 13.80759 13.55649 13.24330 13.31301\n[1265] 13.20415 13.15346 13.73024 13.16009 13.35623 13.36317 13.82170 13.75355\n[1273] 13.21885 13.22875 13.54384 13.42900 13.34740 13.34197 13.31297 13.20783\n[1281] 13.60380 13.37337 13.18672 13.25815 13.29116 13.61049 13.13197 13.76558\n[1289] 13.35926 13.33375 13.31234 13.32400 13.24496 13.25881 13.84503 13.40552\n[1297] 13.29190 13.31733 13.33601 13.41615 13.46143 13.45728 13.33805 13.18254\n[1305] 13.22083 13.60591 13.45313 13.43417 13.30197 13.22970 13.31587 13.44483\n[1313] 13.26664 13.23437 13.71089 13.23316 13.23608 13.32330 13.49760 13.29244\n[1321] 13.39650 13.78788 13.50173 13.54345 13.44852 13.28107 13.35550 13.20019\n[1329] 13.27509 13.22597 13.37497 13.27673 13.48147 13.28818 13.54907 13.69971\n[1337] 13.17493 13.35683 13.22914 13.39922 13.32472 13.35831 13.74027 13.22633\n[1345] 13.28690 13.27522 13.54389 13.17094 13.78287 13.29519 13.25780 13.30965\n[1353] 13.49688 13.70757 13.32425 13.15006 13.30205 13.53449 13.24640 13.29207\n[1361] 13.18160 13.43960 13.11745 13.15558 13.43443 13.34211 13.33496 13.23884\n[1369] 13.46570 13.15688 13.24534 13.34581 13.78960 13.17305 13.17123 13.27281\n[1377] 13.70014 13.32860 13.44517 13.22279 13.36288 13.39137 13.25840 13.19673\n[1385] 13.43078 13.69155 13.37399 13.38509 13.43397 13.53339 13.71017 13.30044\n[1393] 14.01753 13.28067 13.45774 13.24197 13.39209 13.30381 13.36200 13.16316\n[1401] 13.37119 13.33364 13.20946 13.54498 13.35950 13.35671 13.18695 13.24961\n[1409] 13.39275 13.39253 13.76519 13.21284 13.41365 13.16879 13.19912 13.10693\n[1417] 13.25101 13.45723 13.43005 13.32973 13.24002 13.26852 13.32835 13.45955\n[1425] 13.80041 13.26372 13.31882 13.52439 13.41432 13.33797 13.24504 13.39570\n[1433] 13.42006 13.90447 13.29659 13.42827 13.58467 13.64611 13.63713 13.31313\n[1441] 13.17850 13.21551 13.20893 13.30511 13.63879 13.45501 13.25455 13.41595\n[1449] 13.41070 13.54126 13.26280 13.43304 13.43949 13.60616 13.30675 13.39062\n[1457] 13.35510 13.13017 13.32976 13.26572 13.33014 13.21538 13.26645 13.29972\n[1465] 13.43088 13.41520 13.25178 13.16330 13.83755 13.29917 13.24648 13.22979\n[1473] 13.32769 13.34368 13.22030 13.56192 13.29304 13.48411 13.55056 13.28767\n[1481] 13.21503 13.46406 13.19940 13.23398 13.52903 13.09882 13.89172 13.26721\n[1489] 13.27716 13.36588 13.35084 13.27081 13.41759 13.31648 13.33059 13.41760\n[1497] 13.40084 13.64149 13.40119 13.32112\n```\n\n\n:::\n:::\n\n\n## 10 Building a Geographically Weighted Random Forest Model (GWRF)\n\nGWRF, using the `grf()` function from the SpatialML package, combines the predictive power of Random Forest with local spatial modeling. It is expected to improve performance by accounting for geographical variations in feature relationships without relying on parametric assumptions.\n\nWe will calibrate a model to predict HDB resale price by using `grf()` of **SpatialML** package.\n\n### 10.1 Preparing Spatial Data for GWRF\n\nThe `grf()` function does not accept sf or sp objects directly; it requires a standard data frame (dframe) and separate coordinate columns (coords). We must extract the coordinates from our filtered spatial data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Extract Coordinates from filtered data\ncoords_train <- st_coordinates(train_data_filtered)\ncoords_test  <- st_coordinates(test_data_filtered)\n\n# 2. Create non-spatial data frames for the 'dframe' argument,\ntrain_gwrf <- train_data_filtered %>%\n  st_drop_geometry()\n\ntest_gwrf <- test_data_filtered %>%\n  st_drop_geometry()\n\n# Check dimensions\ncat(\"GWRF Training data dimensions:\", dim(train_gwrf), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGWRF Training data dimensions: 3500 26 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"GWRF Test data dimensions:\", dim(test_gwrf), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGWRF Test data dimensions: 1500 26 \n```\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "Take-home_Ex3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}