{
  "hash": "0bc563a1649dbfeabe72d8a7222ec13d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3: Spatio-Temporal Point Patterns Analysis\"\nauthor: \"Emma Chew En Chin\"\ndate: \"Sep 11, 2025\"\ndate-modified: \"last-modified\"\nformat: html\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n\n\n## 1 Overview\n\nA spatio-temporal point process (also called space-time or spatial-temporal point process) is a random collection of points, where each point represents the time and location of an event.\n\nSpatio-temporal point patterns analysis can be used to determine the following: - Arrival of new points in a space across time\n\n-   Removal of existing points in a space across time\n-   Movement of existing points in a space across time\n-   How the entire set of points may be distributed/clustered in a space across time\n\n## 2 Research Context\n\nThe research objectives are:\n\n-   To find out if the locations of forest fire in Kepulauan Bangka Belitung **spatial and spatio-temporally independent**?\n-   If they are not spatio-temporally independent, where and when the observed forest fire locations **tend to cluster?**\n\n### 2.1 Installing and Loading the R packages\n\n-   `raster` : for handling raster data (grid of pixels) in R\n-   `spatstat` : performing Spatial Point Patterns Analysis such as kcross, Lcross, etc\n-   `sparr` : provides functions to estimate fixed and adaptive kernel-smoothed spatial relative risk surfaces via the density-ratio method and perform subsequent inference. Fixed-bandwidth spatiotemporal density and relative risk estimation is also supported\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, raster, spatstat, sparr, tmap, tidyverse)\n```\n:::\n\n\n\n### 2.2 Importing Datasets and Preparing Study Area\n\nImport the ESRI Shapefile, and conduct coordinate projection.\n\nTo determine the EPSG code, check [EPSG.io](EPSG.io) and search for country name + zone number.\n\nZone number can be derived using coordinates:\n\n-   Zone number = floor((longitude + 180) / 6) + 1\n-   For longitude \\~106-107°E: Zone = floor((106 + 180) / 6) + 1 = **Zone 48**\n-   Hence, Kepulauan Bangka Belitung is located in **UTM Zone 48S**, which gives us EPSG code of 32748 when searching in EPSG.io.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_sf <- st_read(dsn=\"data/geospatial\",\n               layer = \"Kepulauan_Bangka_Belitung\") %>%\n  st_union() %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 32748)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kepulauan_Bangka_Belitung' from data source \n  `C:\\emmachew\\ISSS626-emma-chew-en-chin\\Hands-on Exercise\\Hands-on_Ex3\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 297 features and 26 fields\nGeometry type: POLYGON\nDimension:     XYZ\nBounding box:  xmin: 105.1085 ymin: -3.116593 xmax: 106.8488 ymax: -1.501603\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n### 2.3 Converting into OWIN object\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_owin <- as.owin(kbb_sf)\nkbb_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwindow: polygonal boundary\nenclosing rectangle: [512066.8, 705559.4] x [9655398, 9834006] units\n```\n\n\n:::\n:::\n\n\n\nUse class() to confirm that the output is an owin object.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(kbb_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n:::\n\n\n\n### 2.4 Importing and Preparing Forest Fire data\n\nForest Fire data is imported and coordinate projection is conducted.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- read_csv(\"data/geospatial/forestfires.csv\") %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"),\n                       crs = 4326) %>%\n  st_transform(crs = 32748)\n```\n:::\n\n\n\nAs ppp object only accepts numerical or character as mark. The code chunk below is used to convert data type of acq_date to numeric.\n\nFrom this conversion we can also aggregate the dates at a month and day level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_sf %>% \n  mutate(DayofYear = yday(acq_date)) %>%\n  mutate(Month_num = month(acq_date)) %>%\n  mutate(Month_fac = month(acq_date, \n                           label = TRUE, \n                           abbr = FALSE)) %>%\n  mutate(Week_num = week(acq_date)) %>%\n  mutate(Week_fac = month(acq_date, \n                           label = TRUE, \n                           abbr = FALSE))\n```\n:::\n\n\n\n## 3 Visualising the Fire Points\n\nA point symbol map is plotted to show the distribution of fire points.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n### 3.1 Visualising Geographic distribution of forest fires by month\n\nUsing tmap_arrange, we can arrange the monthly maps in a 4 x 3 grid.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots(size = 0.3) +\ntm_facets(by=\"Month_fac\", \n            free.coords=FALSE, \n            drop.units = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-8-1.png){width=100%}\n:::\n:::\n\n\n\n## 4 Computing STKDE by Month\n\nSpattemp.density() of sparr package is used to compute STKDE.\n\n### 4.1 Extracting forest fires by month\n\nRemove unwanted fields from fire_sf dataframe, as `as.ppp()` only needs the mark field and geometry field.\n\nNote that as both `sf` and `raster` are loaded, the `select()` function uses `raster::select()` method, which does not work for sf objects. Hence, we indicate `dplyr::select()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month <- fire_sf %>% \n  dplyr::select(Month_num)\n```\n:::\n\n\n\n### 4.2 Creating ppp object\n\nCreate ppp object and check if output is in correct object class.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_ppp <- as.ppp(fire_month)\nfire_month_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 741 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 695791] x [9658137, 9828767] units\n```\n\n\n:::\n:::\n\n\n\nEnsure that output is numeric.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fire_month_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  741 points\nAverage intensity 2.49258e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.579  10.000  12.000 \n\nWindow: rectangle = [521564.1, 695791] x [9658137, 9828767] units\n                    (174200 x 170600 units)\nWindow area = 29728200000 square units\n```\n\n\n:::\n:::\n\n\n\nCheck for any duplicated point events.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(fire_month_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n### 4.3 Including owin object\n\nCombine ppp and owin objects.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_owin <- fire_month_ppp[kbb_owin]\nsummary(fire_month_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  741 points\nAverage intensity 6.42469e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.579  10.000  12.000 \n\nWindow: polygonal boundary\nsingle connected closed polygon with 47493 vertices\nenclosing rectangle: [512066.8, 705559.4] x [9655398, 9834006] units\n                     (193500 x 178600 units)\nWindow area = 11533600000 square units\nFraction of frame area: 0.334\n```\n\n\n:::\n:::\n\n\n\nPlotting ff_owin to check the correctness of an output object.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_month_owin)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-14-1.png){width=100%}\n:::\n:::\n\n\n\n### 4.4 Computing Spatio-temporal KDE\n\nUsing `spattemp.density()` from the sparr package STKDE can be computed.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_kde <- spattemp.density(fire_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15102.47 (spatial)\n  lambda = 0.0304 (temporal)\n\nNo. of observations\n  741 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 705559.4] x [9655398, 9834006]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [1.233458e-27, 8.202976e-10]\n```\n\n\n:::\n:::\n\n\n\nFrom the output, we can infer that:\n\n-   temporal value = 0.0304, showing that clusters are highly concentrated in specific months\n\n### 4.5 Plot the Spatio-temporal KDE object\n\nKDE is plotted for July-December 2023.\n\nFrom the KDE plots, we can observe that forest fires begin in the northern area from July, and forest fires appear with greater frequency in September. It is only until end November that forest fires subside.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(7,8,9,10,11,12)\npar(mfcol=c(2,3))\nfor(i in tims){ \n  plot(st_kde, i, \n       override.par=FALSE, \n       fix.range=TRUE, \n       main=paste(\"KDE at month\",i))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-16-1.png){width=100%}\n:::\n:::\n\n\n\n## 5 Computing STKDE by Day of Year\n\n### 5.1 Creating ppp object\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_ppp <- fire_sf %>% \n  dplyr::select(DayofYear) %>%\n  as.ppp()\n```\n:::\n\n\n\n### 5.2 Including owin object\n\nCombining both ppp and owin objects.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_owin <- fire_yday_ppp[kbb_owin]\nsummary(fire_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  741 points\nAverage intensity 6.42469e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   10.0   213.0   258.0   245.9   287.0   352.0 \n\nWindow: polygonal boundary\nsingle connected closed polygon with 47493 vertices\nenclosing rectangle: [512066.8, 705559.4] x [9655398, 9834006] units\n                     (193500 x 178600 units)\nWindow area = 11533600000 square units\nFraction of frame area: 0.334\n```\n\n\n:::\n:::\n\n\n\n### 5.3 Computing Spatio-temporal KDE\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(\n  fire_yday_owin)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15102.47 (spatial)\n  lambda = 6.3198 (temporal)\n\nNo. of observations\n  741 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 705559.4] x [9655398, 9834006]\n\nTemporal bound\n  [10, 352]\n\nEvaluation\n  128 x 128 x 343 trivariate lattice\n  Density range: [3.959516e-27, 2.751287e-12]\n```\n\n\n:::\n:::\n\n\n\nFrom the output, we can infer that:\n\n-   temporal value = 6.3198, showing that clusters are formed across ~ 6 days, which is around a week\n\nWhile we can plot maps for each day, there will be clearer temporal shifts when we look at the fire points by week.\n\n## 6 Computing STKDE by Week\n\n### 6.1 Extracting forest fires by week\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_week <- fire_sf %>% \n  dplyr::select(Week_num)\n```\n:::\n\n\n\n### 6.2 Creating ppp object\n\nCreate ppp object and check if output is in correct object class.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_week_ppp <- as.ppp(fire_week)\nfire_week_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 741 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 695791] x [9658137, 9828767] units\n```\n\n\n:::\n:::\n\n\n\nEnsure that output is numeric.\n\nCheck for any duplicated point events.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(fire_week_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n### 6.3 Including owin object\n\nCreate a ppp object that is configured at a week level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweek_range <- range(fire_sf$Week_num, na.rm = TRUE)\nprint(paste(\"Week range:\", week_range[1], \"to\", week_range[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Week range: 2 to 51\"\n```\n\n\n:::\n\n```{.r .cell-code}\nst_window <- list(\n  xrange = kbb_owin$xrange,  # Spatial x bounds\n  yrange = kbb_owin$yrange,  # Spatial y bounds\n  trange = week_range        # Temporal bounds (your Week_num range)\n)\n\nfire_stppp <- fire_week_ppp\nfire_stppp$window <- st_window\n```\n:::\n\n\n\nCombine ppp and owin objects.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_week_owin <- fire_week_ppp[kbb_owin]\nsummary(fire_week_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  741 points\nAverage intensity 6.42469e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   2.00   31.00   37.00   35.59   41.00   51.00 \n\nWindow: polygonal boundary\nsingle connected closed polygon with 47493 vertices\nenclosing rectangle: [512066.8, 705559.4] x [9655398, 9834006] units\n                     (193500 x 178600 units)\nWindow area = 11533600000 square units\nFraction of frame area: 0.334\n```\n\n\n:::\n:::\n\n\n\n### 6.4 Computing Spatio-temporal KDE\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_week <- spattemp.density(\n  fire_week_owin)\nsummary(kde_week)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15102.47 (spatial)\n  lambda = 0.8897 (temporal)\n\nNo. of observations\n  741 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 705559.4] x [9655398, 9834006]\n\nTemporal bound\n  [2, 51]\n\nEvaluation\n  128 x 128 x 50 trivariate lattice\n  Density range: [6.879808e-26, 1.831022e-11]\n```\n\n\n:::\n:::\n\n\n\n### 6.5 Plot the Spatio-temporal KDE object\n\nKDE is plotted by week.\n\nWe can see that from Week 30 (~ end July), there are more forest fires occurring in the northern parts of the area.\n\nFrom Week 38 (~ mid September), the southern parts of the area experience more forest fires, and occurrences increase until Week 46 (~ mid November), where they start to reduce in number.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- seq(2,51)\npar(mfcol=c(2,3))\nfor(i in tims){ \n  plot(kde_week, i, \n       override.par=FALSE, \n       fix.range=TRUE, \n       main=paste(\"KDE at week\",i))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-4.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-5.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-6.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-7.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-8.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-26-9.png){width=100%}\n:::\n:::",
    "supporting": [
      "Hands-on_Ex3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}