---
title: "3b: Importing and preparing data for Take-home Exercise 1"
author: "Emma Chew En Chin"
date: "Sep 13, 2025"
date-modified: "last-modified"
format: html
execute: 
  echo: true
  eval: true
  warning: false
  freeze: true
---

### Importing R Packages

```{r}
pacman::p_load(sf, tmap, spatstat, tidyverse, httr)
```

### Importing ACRA Data

```{r}
folder_path <- "data/aspatial/acra"
file_list <- list.files(path = folder_path,
                        pattern = "^ACRA*.*\\.csv$", 
                        full.names = TRUE)
acra_data <- file_list %>%
    map_dfr(read_csv, show_col_types = FALSE)
```

```{r}
write_rds(acra_data,
          "data/rds/acra_data.rds")
```

### Tidying ACRA data

```{r}
# Create MONTH_NUM (e.g. 1, 2, 3) and MONTH_ABBR (e.g. Jan, Feb, Mar)
biz_56111 <- acra_data %>%
  select(1:24) %>%
  filter(primary_ssic_code == 56111) %>%
  rename(date = registration_incorporation_date) %>%
  mutate(date = as.Date(date),
         YEAR = year(date),
         MONTH_NUM = month(date),
         MONTH_ABBR = month(date,
                            label = TRUE,
                            abbr = TRUE)) %>%
  # if the postal code is 5 digits, add 0 in front
  mutate(
    postal_code = str_pad(postal_code, 
                    
    width = 6, side = "left", pad = "0")) %>% 
        filter(YEAR ==  2025)

```

### Geocoding

Extract unique postal code Use OneMap to do reverse geocoding

```{r}
postcodes <- unique(biz_56111$postal_code)

url <- "https://onemap.gov.sg/api/common/elastic/search"

# Found: geocoded, Not found: cannot be geocoded (e.g.) New development area or inaccurate postal code
found <- data.frame()
not_found <- data.frame(postcode = character())

for (pc in postcodes) {
  query <- list(
    searchVal = pc,
    returnGeom = "Y",
    getAddrDetails = "Y",
    pageNum = "1"
  )
  
  res <- GET(url, query = query)
  json <- content(res)
  
  if (json$found != 0) {
    df <- as.data.frame(json$results, stringsAsFactors = FALSE)
    df$input_postcode <- pc 
    found <- bind_rows(found, df)
  } else {
    not_found <- bind_rows(not_found, data.frame(postcode = pc))
  }
}
```

### Appending the location information

```{r}
biz_56111 = biz_56111 %>%
  left_join(found, 
            by = c('postal_code' = 'POSTAL'))
```

### Saving the data

```{r}
saveRDS(biz_56111, file = "data/rds/biz_56111_joined.rds")
```

### Loading the data and using X & Y coordinates as SVY21 projection

```{r}
biz_56111_fixed <- biz_56111 %>%
  mutate(across(where(~is.factor(.) && nlevels(.) < 2), as.character))

biz_56111_sf <- st_as_sf(biz_56111_fixed,
                         coords = c("X", "Y"), # Lowercase 'c'
                         crs = 3414)

class(biz_56111_sf)
plot(st_geometry(biz_56111_sf))
```
