---
title: "1: Geospatial Analytics for New Retail Store Development"
author: "Emma Chew En Chin"
date: "Sep 11, 2025"
date-modified: "last-modified"
format: html
execute: 
  echo: true
  eval: true
  warning: false
  freeze: true
---

## 1 Overview

### 1.1 Data Sets

## 2 Preparing Data for Analysis

### 2.1 Load R Packages

```{r}
pacman::p_load(sf, tmap, spatstat, tidyverse, httr)
```

::: callout-note
-   **sf:**
-   **tmap:**
-   **httr:** provides a wrapper for the curl package
-   **dplyr:** from sf, used for data manipulation
-   **lubridate:** used to handle date and date-time data type
:::

### 2.2 Import and Analyse Business Entity Data

Data from ACRA is merged into one single dataframe.

```{r}
# List all files in folder
folder_path <- "data/aspatial/acra"
file_list <- list.files(path = folder_path,
                        pattern = "^ACRA*.*\\.csv$", 
                        full.names = TRUE)
acra_data <- file_list %>%
  map(~ read_csv(.x)) %>%
  bind_rows()

glimpse(acra_data)
```

```{r}
live_companies <- acra_data %>%
  filter(str_detect(entity_status_description, "^Live"))
glimpse(live_companies)
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```